### PR TITLE
Multiple improvements to grid export files

### PR DESCRIPTION
**Pull request by chrismcgrath**
# Contributor Agreement
_Have you filled out and sent your [Spark Contributor Agreement](http://www.rockrms.com/Content/RockExternal/Misc/Contributor%20Agreement.pdf) to secretary [at] sparkdevnetwork.org?_

Yes

# Context
_What is the problem you encountered that lead to you creating this pull request?_

Initially, I found that exporting a Dynamic Data Block resulted in a spreadsheet that did not have any Date or Number formatting. I also found that a single formatting for Dates and Numbers did not always make sense, such as showing the hours and minutes on a BirthDate column, or showing some currency columns with decimal and others as text with a dollar sign. Finally, I found some other miscellaneous bugs such as extra rows/columns being added, and the column headers not being included in the frozen header section.

# Goal
_What will this pull request achieve and how will this fix the problem?_

All grids will intelligently format their exported spreadsheets in a common way, no matter what kind of data source is used to populate the grid.

# Strategy
_How have you implemented your solution?_

* Improved formatting of dates and numbers to choose the most logical formatting based on the data in the column
	- Column will be formatted to show the date only (no time) if none of the fields in the column have a time component
	- Column will show decimal places only if there is a decimal value in any of the cells of the column, or it's a currency field
	- Template fields that are populated using the FormatAsCurrency() function will format the value as a decimal rather than text using the ReverseCurrencyFormatting() function
* Added proper formatting of dates and numbers for dynamic data block exports
* Worksheet title, header text, and file name will now use title of the page the grid is on if there is no grid caption set.
* No longer adds an extra row and column in some cases
* Now correctly includes the column headers in the frozen header section
* Created an ExcelHelper class to house common Excel exporting functionality (see https://github.com/SparkDevNetwork/Rock/pull/1852)

# Possible Implications
_What could this change potentially impact? Are there any security considerations? Where could this potentially affect backwards compatibility?_

I tried to think of the most common uses of number columns and format them in a meaningful way. I'm sure that not every possibility has been covered here, but the result should be an improvement over totally unformatted columns. The only place the data itself is being exported differently is for grids like the Event Registration grid where dollar amounts are displayed as text in a template field, but are now exported as decimals.

# Screenshots
_Provide us some screenshots if your pull request either alters existing UI or provides new UI. Arrows and labels are helpful._
## Example 1
Example showing Data View of pledge data
**Before**
image
> Note the position of the freeze pane (light gray line) above the header on the third row.

**After**
image
> Note the corrected position of the freeze pane (light gray line) _below_ the header on the third row.

## Example 2
Showing Report based on previous example's Data View.
**Before**
image

**After**
image

# Documentation
_If your change effects the UI or needs to be documented in one of the existing [user guides](http://www.rockrms.com/Learn/Documentation), please provide the brief write-up here:_

### CODE REVIEW

**Comment by azturner** [comment]
@chrismcgrath This appears to have some issues if the grid does not have any records. Realize that a user probably wouldn't bother exporting an empty table, but if they do, it should probably still show excel file with headers rather than causing an error. Is that something you can take a look at?

**Comment by chrismcgrath** [comment]
I should have tested that... I'll take a look this week.

Get Outlook for Android<https://aka.ms/ghei36>



On Mon, Dec 5, 2016 at 6:22 PM -0600, "David Turner" <notifications@github.com<mailto:notifications@github.com>> wrote:


@chrismcgrath<https://github.com/chrismcgrath> This appears to have some issues if the grid does not have any records. Realize that a user probably wouldn't bother exporting an empty table, but if they do, it should probably still show excel file with headers rather than causing an error. Is that something you can take a look at?

-

**Comment by dcs619** [comment]
@chrismcgrath I can't tell you how many tickets I just closed after pulling in this fix!  Thanks so much!

**Comment by chrismcgrath** [comment]
@azturner I was just looking at this and not able to reproduce the problem you describe. Could you let me know if this is still an issue and exactly how to reproduce it, including which grid you're trying to export? Thanks!

**Pull request merged**
