### PR TITLE
Ensure the paymentInfo object that is sent to the gateway contains `BusinessName` if someone is giving as a business

### PR DESCRIPTION
**Pull request by taylorbrooks**
## Proposed Changes

Fixes: #5788

## Types of changes

What types of changes does your code introduce to Rock?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality, which has been approved by the core team)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] This is a single-commit PR. (If not, please squash your commit and re-submit it.)
- [x] I verified my PR does not include whitespace/formatting changes -- because if it does it will be closed without merging.	
- [x] I have read the [Contributing to Rock](https://github.com/SparkDevNetwork/Rock/blob/master/.github/CONTRIBUTING.md) doc
- [x] By contributing code, I agree to license my contribution under the [Rock Community License Agreement](https://www.rockrms.com/license)
- [ ] Unit tests pass locally with my changes
- [ ] I have added any required [unit tests](https://github.com/SparkDevNetwork/Rock/blob/develop/Rock.Tests.UnitTests/README.md) or [integration tests](https://github.com/SparkDevNetwork/Rock/blob/develop/Rock.Tests.Integration/README.md) that prove my fix is effective or that my feature works
- [ ] I have included updated language for the [Rock Documentation](https://www.rockrms.com/Learn/Documentation) (if appropriate)

### CODE REVIEW

**Comment by taylorbrooks** [comment]
Hi @chead4, is there anything I need to do to have this issue and changes reviewed?

**Comment by chead4** [comment]
@taylorbrooks Hi Taylor Thanks for reaching out and for providing a pull request for the issue.  Issue 5788 along with this pull request is in our development queue, and while we're addressing a few other issues, we anticipate reaching this one shortly.

**Comment by taylorbrooks** [comment]
Hi @chead4, just nudging the thread again.

Any update on this in the development queue?

**Comment by chead4** [comment]
@taylorbrooks Hi Taylor - Thanks for the nudge.  We haven't forgotten about this issue  - there are a few issues ahead of this one and it's making its way to the top of our queue.  I will provide another update next week here in git hub.

**Comment by nairdo** [comment]
Since the primary developer was about to start a different project, I had him jump on this first since it was a pretty small change (https://github.com/SparkDevNetwork/Rock/commit/23d6b127ccdbfc336dc0d5127e4294ca82f89774). The change will be in v16.6

**Comment by taylorbrooks** [comment]
Thanks @nairdo!

**Pull request closed without merging**
