### PR TITLE
Fixed infinite loop when too few check-in codes can be computed

### PR DESCRIPTION
**Pull request by dcs619**
# Contributor Agreement
_Have you filled out and sent your [Spark Contributor Agreement](http://www.rockrms.com/Content/RockExternal/Misc/Contributor%20Agreement.pdf) to secretary [at] sparkdevnetwork.org?_

# Context
_What is the problem you encountered that lead to you creating this pull request?_

See initial discussion at #2330.  I've limited the number of loops to the possible number of checkin codes: [# of alpha or numeric character codes] ^ [desired code length].  Since the Generate() method may pick the same no-good twice, this may stop the loop before it finds the last possible code, but the list would be close to exhausted before the loop does stop.

@cabal95 do you mind testing?

### CODE REVIEW

**Comment by cabal95** [comment]
Yes, I'll work on testing this out.  All I will be testing is checking in on a non-patched branch until it fails and then switch to the this branch to make sure it lets me continue checking in.

**Comment by cabal95** [comment]
That "works", in that it now gives some feedback about the fact it failed. An exception is logged and displayed on the client:

image

I think we should check if the `attendanceCode` is null and if so raise an exception with a message that explicitly states why the exception happened rather than just the generic one that might not make sense to an system administrator. The above exception is from this line where the `GetNew()` method returns null since it couldn't generate any attendance code.

https://github.com/SparkDevNetwork/Rock/blob/develop/Rock/Workflow/Action/CheckIn/SaveAttendance.cs#L81

Maybe something as simple as:
```
    if ( attendanceCode == null )
    {
        throw new Exception( "All possible Attendance Codes have been used. Please increase code length." );
    }
```

**Comment by dcs619** [comment]
Yep, I didn't test the workflow action could handle NULL @cabal95. I'll add that in.  I'm not a huge fan of throwing an exception but if I can't find a way to pass a graceful message back that at least would log for a Rock admin to follow up with.

**Comment by cabal95** [comment]
A graceful message would be nice, but I'm personally not that worried about it.  I mean this is the first time we have run into this issue in the history of Rock AFAIK so it's not like this is an error that will pop up a lot.

**Comment by azturner** [comment]
@dcs619 This looks good, but it looks like from the comments that you were going to make another change to handle the null value returned. Are you still planning to make that change?

**Comment by dcs619** [comment]
@azturner Yes it's still on my list. I'm trying to get back to a "clean" working branch so I can test the changes

**Comment by nairdo** [comment]
Greetings @dcs619 , I think David T is passing this to me for follow-up or closing.  It looks like some changes (such as https://github.com/SparkDevNetwork/Rock/commit/4f321c6812023fe3a49527bf5fb1b97b5fdbb1ab#diff-187bba5e6f8c59c9d3c0c92c3f2d5176) since your original PR are causing a merge conflict so you might want to re-PR over the latest stuff when you test.

**Comment by nairdo** [comment]
I'm closing this pull-request, but feel free to re-submit a new one once it's ready.

**Pull request closed without merging**
