### PR TITLE
[EN] FundraisingParticipant Show Amount Setting

### PR DESCRIPTION
**Pull request by nateh777**
## Proposed Changes
Change mentioned in last bullet of discussion #3008 

Added setting to Show/Hide donation amount on contribution list on the FundraisingParticipant block.

image

image

## Types of changes
What types of changes does your code introduce to Rock?
_Put an `x` in the boxes that apply_

* [ ] Bugfix (non-breaking change which fixes an issue)
* [x] New feature (non-breaking change which adds functionality, which has been approved by the core team)
* [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

* [x] I have read the [CONTRIBUTING ](https://github.com/SparkDevNetwork/Rock/blob/master/.github/CONTRIBUTING.md) doc
* [x] By contributing code, I agree to license my contribution under the [Rock Community License Agreement ](https://www.rockrms.com/license)
* [ ] Unit tests pass locally with my changes
* [ ] I have added [REQUIRED tests ](https://github.com/SparkDevNetwork/Rock/blob/develop/Rock.Tests/README.md) to Rock.Tests that prove my fix is effective or that my feature works
* [x] I have included necessary documentation (if appropriate)

## Documentation

**Show Amount**

Determines if the Amount column should be displayed in the Contributions List.

### CODE REVIEW

**Comment by nairdo** [comment]
@nateh777 This PR is missing a migration for the new block setting.

**Comment by nateh777** [comment]
@nairdo migration was added a couple weeks ago, was that okay or did I need to do something differently?

**Comment by nateh777** [comment]
@nairdo @edmistj were any changes needed for this PR? It has been awhile and I noticed it is still sitting out here. I just want to make sure I don't need to change anything on it. It looks like there is a conflict now I may need to resolve.

**Comment by nairdo** [comment]
@nateh777 I will be pulling this in to v9. 

In the future, when you add code for the migration, don't include it in the Migrations project (Rock.Migrations.csproj) otherwise it would be out of sequence with the current migration sequence.  _In these cases, we'll re-generate the actual migration but use your code inside that migration._ 

I just figured out that we must have accidentally removed this from the PR template last year... I'll fix that.  I used to say:

> Migrations
> Should your pull request require a migration, please exclude the migration from the Rock.Migration project, but submit it in your pull request. Please add a note to your pull request that provides a heads up that a migration file is present.

**Pull request merged**
