### PR TITLE
New developer control to provide a Captcha to validate a real person

### PR DESCRIPTION
**Pull request by cabal95**
## Contributor Agreement
_By contributing your code, you agree to license your contribution under the [Rock Community License Agreement](https://www.rockrms.com/license)._

## Context
_What is the problem you encountered that lead to you creating this pull request?_

See #2607. Wanted a central control for providing a Captcha to developers.

## Goal
_What will this pull request achieve and how will this fix the problem?_

Make a control that developers can use in their blocks.

## Strategy
_How have you implemented your solution?_

Implemented new control using Google's reCaptcha system. Chose generic term `Captcha` as the control name so that if we ever change providers we don't have to change the control interface (hopefully).

### Developer information

Control can be used either `Required="true"` or `Required="false"`. When not required it will allow the user to submit the form, but will respond `false` to the `IsResponseValid()` method. This allows blocks to optionally use the control when it isn't strictly required but could help. For example, in a Prayer block it might be optional, but if used would automatically mark the request as approved.

The `IsResponseValid()` method ensures the response is valid and must be used. If Google detects a large amount of non-verified responses it will put a warning on the user's reCaptcha administration console.

It is recommended that all uses of the Captcha control be optional. This is because the administrator must manually enable an account with Google for it's use and as such we cannot be certain that they have done so. And they may choose not to altogether.

@edmistj My last paragraph brings up a question. If the control is used, and the admin has not configured the global attributes, should an error occur (as it would now) or should the control silently mark the user response as valid? That would really only be useful if a developer decided to "hard-code" enable a Captcha control, rendering the block useless to a user who did not have Captcha configured.

### Example Usage

```
<Rock:Captcha ID="cpCaptcha" runat="server" Required="false" Label="Verification" />
```
```
var isValid = cpCaptcha.IsResponseValid();
```

You can also specify the `SiteKey` and `SecretKey` in the Captcha declaration, or in code, if needed for some reason.

## Tests
_If your code is a new method or function (that doesn't need a mock database or SqlServerTypes library) and can be Xunit tested [see example](https://github.com/SparkDevNetwork/Rock/blob/develop/Rock.Tests/Rock/Lava/RockFiltersTests.cs) be sure your pull request includes the corresponding unit tests in the Rock.Tests project. In all cases *you* MUST test your code before submitting a pull request._

## Possible Implications
_What could this change potentially impact? Are there any security considerations? Where could this potentially affect backwards compatibility?_

Spam might decrease.

## Screenshots
_Provide us some screenshots if your pull request either alters existing UI or provides new UI. Arrows and labels are helpful._

Screenshots show the "Required=True" state of the control in both an invalid and valid state.

2018-01-22 14_13_19-virtualbox

<hr />

2018-01-22 14_13_53-virtualbox

## Documentation
_If your change effects the UI or needs to be documented in one of the existing [user guides](http://www.rockrms.com/Learn/Documentation), please provide the brief write-up here:_

We need documentation written up on how to register for reCaptcha use. It is pretty straight forward, the summary of steps is below:

* https://www.google.com/recaptcha/admin
* Register a new site (unless you already have one)
* Label = "RockRMS"
* Style = reCAPTCHA V2
* Domains = top level domains (e.g. rocksolidchurchdemo.com)

I learned something helpful while doing this. It is top level domains. So if you put in rocksolidchurchdemo.com, you do not also need to put in www.rocksolidchurchdemo.com. It acts as a wildcard for all child domains. This makes configuration even easier.

## Migrations
Should your pull request require a migration, please exclude the migration from the Rock.Migration project, but submit it in your pull request. Please add a note to your pull request that provides a heads up that a migration file is present.

A migration is included (though not in the project file) to create the 2 Global Attributes to store the Site Key and Secret Key.

### CODE REVIEW

**Comment by edmistj** [comment]
@cabal95 could `.IsResponseValid()` return a bool? where null is returned when not enabled. That would let the developer decide what to do.

**Comment by cabal95** [comment]
That would be doable. In such a case if either SiteKey or SecretKey are empty then the control would not render (treated as if Visible=false) and `.IsResponseValid()` would return null.

I also just realized I didn't complete my original thought on this. The downside to something like this is less information for the admin when trying to figure out "why the bloody captcha isn't showing" and not realizing it's because they haven't put in the SiteKey or SecretKey, since no visible error would show. e.g. admin enables `Use Captcha` in the block settings, clicks save, and then nothing changes. No captcha is shown vs an error stating it's mis-configured.

**Comment by cabal95** [comment]
Another possible take on this that might be better, is a new method of `.IsAvailable()` on the control that returns a `bool` indicating if the control is available (i.e. has the sitekey and secretkey). This would allow the developer to device what to do _before_ rendering the page.

**Comment by edmistj** [comment]
@cabal95  that works

**Comment by cabal95** [comment]
All set. Realized there was no reason to make it a method so there is a `.IsAvailable` property now.

**Comment by edmistj** [comment]
@cabal95 could you write up some documentation for this feature. Amy can touch it up a bit, but at this point I'm not sure we'd even know where to start.

**Comment by cabal95** [comment]
@edmistj Will do. Should I update the `UI Toolkit` wiki page as well?

**Comment by edmistj** [comment]
@cabal95 that would be nice, thanks!

**Comment by cabal95** [comment]
Wiki updated and documentation sent to Amy.

**Comment by azturner** [comment]
Thanks for documenting this @cabal95 . We have standardized on prefixing all future core attributes with 'core_' so I updated these to reflect that: https://github.com/SparkDevNetwork/Rock/commit/6c2a887329684005473d8b46ece355c93f9520e1

**Comment by cabal95** [comment]
👍 I thought that was the case but looked at another recent migration and didn't notice the core_, but probably looked at the one that didn't get the memo. :)

**Pull request merged**
