### PR TITLE
Provide helper classes for plugin developers to use theme colors

### PR DESCRIPTION
**Pull request by dcs619**
@edmistj Current theme colors are included on control styles, but aren't accessible by themselves.  This adds a couple classes for plugin developers to use themes without using the exact control style. 

It looks like _helpers.less was designed to do something similar, but that's not included anywhere & it didn't compile when I added it.

Side note: the latest Web Essentials is stable and auto-recompiles on save.

### CODE REVIEW

**Comment by edmistj** [comment]
I’d like to get the _helpers.less working for check-in (there’s a few other classes that would be nice to have). I’m wondering if you can use the @accent-xxxx-colors instead of the .primary colors. That would make it more consistent with the core themes. I pushed a change that adds this. Let me know if you have questions.

**Comment by dcs619** [comment]
@edmistj accent-xxxx colors are only set to the button color; we need the background and text colors as well.  

Can I add classes of bg-color and text-color so they're consistent?

**Comment by edmistj** [comment]
Is this what you were thinking?

.bg-color {
    background-color: @body-bg;
}

.text-color {
    color: @text-color;
}

**Comment by dcs619** [comment]
@edmistj Yep!  However, Rock themes use @body-bg for background color, and Check-in themes use @bg-color.  Can we make that variable name consistent?  I'll update the PR.

**Comment by dcs619** [comment]
Whoops, just saw you already made those consistent.  Thanks!

**Comment by edmistj** [comment]
OK, let me know if there is anything else you need.
-Jon



[jon-sig]

**Pull request closed without merging**
