### PR TITLE
Add support for ViewState compression with ratio of about 15:1.

### PR DESCRIPTION
**Pull request by cabal95**
# Contributor Agreement
_Have you filled out and sent your [Spark Contributor Agreement](http://www.rockrms.com/Content/RockExternal/Misc/Contributor%20Agreement.pdf) to secretary [at] sparkdevnetwork.org?_

Yes

# Context
_What is the problem you encountered that lead to you creating this pull request?_

Extremely slow postback of pages due to large ViewState size.

# Goal
_What will this pull request achieve and how will this fix the problem?_

Apply GZIP compression to the ViewState.

# Strategy
_How have you implemented your solution?_

A new subclass of PageStatePersister has been added to the Rock.dll and RockPage class has been updated to override the property getter that retrieves it.

Compression of ViewState using GZIP algorithm is performed if the ViewState is greater than 100KB. The achieved compression ratio is between 15:1 and 20:1. A ViewState that was previously 1.5MB becomes 73KB.

# Possible Implications
_What could this change potentially impact? Are there any security considerations? Where could this potentially affect backwards compatibility?_

Should not impact backwards compatibility beyond a user trying to re-post a page generated from before this patch is applied to a page generated after this patch is applied (unlikely, and would probably throw an exception either way). Security should not be affected as we still encrypt the ViewState with the Machine Key.

# Screenshots
_Provide us some screenshots if your pull request either alters existing UI or provides new UI. Arrows and labels are helpful._

screen shot 2016-12-28 at 12 40 36 pm

# Documentation
_If your change effects the UI or needs to be documented in one of the existing [user guides](http://www.rockrms.com/Learn/Documentation), please provide the brief write-up here:_

n/a

# Comments

This patch works as is, but a possible improvement would be to have a Global Attribute that the Admin could set for the threshold at which to compress ViewState (or disable it completely). That would, however, require migration scripts and I'm not really up to speed enough to tackle that just yet.

### CODE REVIEW

**Comment by cabal95** [comment]
I looked into providing this as a Plugin, but it would have requires the user to setup a Browser/ file with a PageAdapter setting.  And only one PageAdapter per matched browser can be specified (so documentation says) so that did not seem like a good option.

**Comment by dcs619** [comment]
@cabal95 Praise be.  This would fix #1441.

**Comment by mikepetersonccv** [comment]
@cabal95 this sounds like an awesome enhancement!! BTW, regarding Out Of Memory with IISExpress, you can configure Visual Studio to run the 64bit Version of IIS Express 
image

**Comment by cbump** [comment]
Just as an FYI we merged this and have been running this in our production environment for about a month with no issues.

**Comment by edmistj** [comment]
Great, I have a feature branch that also adds the ability to view the control structure of the viewstate (to help eliminate unneeded viewstate bulk) that I want to merge in with @cabal95 's compression. Was hoping to get to this today but ran out of time. I'll try to get it merged in the next week.

**Comment by cabal95** [comment]
@cbump Thanks for taking the bullet to try this out in production!

**Comment by edmistj** [comment]
@cabal95 I merged this with the changes I ha. You might code review it if you get a chance.

**Pull request merged**
