### PR TITLE
+ Added toggle button to Show/Hide Data View and Report Results.

### PR DESCRIPTION
**Pull request by MrUpsideDown**
(Implements #1191)

### CODE REVIEW

**Comment by edmistj** [comment]
@MrUpsideDown FYI... I made a few tweaks to bring this back into our UI patterns.

**Comment by MrUpsideDown** [comment]
@edmistj Ok, thanks. I was winging it, just using bits of what I found elsewhere. Is there a better way to find out which styles/classes are appropriate in different circumstances?

**Comment by edmistj** [comment]
@MrUpsideDown welllll... no.... Someday I'd like to have a nice UI standards guide. But until we're not scrambling to keep up it's on the back burner.

**Comment by MrUpsideDown** [comment]
@edmistj Understood... I just wanted to be sure I'm following the standards as best I can. Until the guide exists, you may have to tweak a few more of my contributions in the future, sorry!

**Pull request merged**
