### PR TITLE
Fixed check-in configuration getting out of sync when editing a check-in group in Group Details page.

### PR DESCRIPTION
**Pull request by cabal95**
## Proposed Changes
If you have a Check-in Group type set to Show in Navigation, you are able to change that check-in group's schedule and location configuration from the Group Details page. Previously, this page did not flush the check-in cache which would leave the check-in state out of sync from the database.

If the group had GroupLocation data that has been modified then the check-in cache is emptied upon save. Used the `GroupMemberWorkflowTrigger` logic in the same method as a template for implementing conditional cache flushing so we don't flush the cache every time any group is saved.

Fixes: #2975

## Types of changes
What types of changes does your code introduce to Rock?
_Put an `x` in the boxes that apply_

* [x] Bugfix (non-breaking change which fixes an issue)
* [ ] New feature (non-breaking change which adds functionality, which has been approved by the core team)
* [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

* [x] I verified my PR does not include whitespace/formatting changes -- because if it does it will be closed without merging. 
* [x] I have read the [Contributing to Rock ](https://github.com/SparkDevNetwork/Rock/blob/master/.github/CONTRIBUTING.md) doc
* [x] By contributing code, I agree to license my contribution under the [Rock Community License Agreement ](https://www.rockrms.com/license)
* [ ] Unit tests pass locally with my changes
* [ ] I have added [required tests ](https://github.com/SparkDevNetwork/Rock/blob/develop/Rock.Tests/README.md) that prove my fix is effective or that my feature works
* [ ] I have included updated language for the [Rock Documentation ](https://www.rockrms.com/Learn/Documentation) (if appropriate)

## Further comments
n/a

## Documentation
n/a

### CODE REVIEW

**Comment by nairdo** [comment]
@cabal95 I'm going to pull this in, but I'm going to add an additional check of the group's grouptype `TakesAttendance` flag so we are only clearing cache on _**all**_ kiosks under the most strict (fewest) conditions.

**Comment by cabal95** [comment]
Sounds good. Didn't know if there was a way to detect if a group was being used for check-in or not.

**Comment by cabal95** [comment]
@nairdo Did this ever get pulled in? Just making sure if I can clean up my branches and such.

**Comment by nairdo** [comment]
@cabal95 No, it was not pulled in at that point.  I did it just now.

**Comment by sparkdevnetwork-service** [comment]
➤ Nick Airdo commented:

Jon Edmiston ( https://app.asana.com/0/20866866924296/list ) Are we really sure...:

  1. ...someone should be editing a check-in group via the normal GroupDetail block?
  2. The GroupDetail block now needs to be  aware of Rock.CheckIn.KioskDevice.
  3. Every time someone edits a group location via the GroupDetail block all the KioskDevices will be cleared from cache.

Even so, perhaps the KioskDevice should only be cleared if the group's group type has a Check-in purpose (Serving Area, Check-in Filter, Check-in Template)?

**Comment by sparkdevnetwork-service** [comment]
➤ Jon Edmiston commented:

Let's add this to a meeting to discuss.

**Comment by sparkdevnetwork-service** [comment]
➤ Nick Airdo commented:

Ok.  My new proposal is that we only perform that Rock.CheckIn.KioskDevice.Clear() if the group's groupType has TakesAttendance = true.  Sound good?

**Comment by sparkdevnetwork-service** [comment]
➤ Jon Edmiston commented:

You'll need to walk me through this. Can you be prepared to do so during our Monday afternoon meeting?

**Pull request merged**
