### PR TITLE
+ Added Data Layer support for notes to have attachments. Fixes (#3090)

### PR DESCRIPTION
**Pull request by cabal95**
## Proposed Changes

In Rock v8, Notes gained the ability to be better used for threading and other discussion type purposes. This PR adds the ability, as discussed offline with Jon, the ability for notes to track attachments.

This only adds support to the tables and the Note Type configuration screen for attachments. It does _not_ add any UI for actually attaching files to notes. But this does allow for plugins to start making use of the table changes and provide attachments when they are using notes for their own purposes.

> Note: This is intended for v9, so hopefully `develop` is the correct branch for that at this point in time.

Fixes: #3090

## Types of changes

What types of changes does your code introduce to Rock?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality, which has been approved by the core team)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [X] I have read the [CONTRIBUTING](https://github.com/SparkDevNetwork/Rock/blob/master/.github/CONTRIBUTING.md) doc
- [X] By contributing code, I agree to license my contribution under the [Rock Community License Agreement](https://www.rockrms.com/license)
- [ ] Unit tests pass locally with my changes
- [ ] I have added [REQUIRED tests](https://github.com/SparkDevNetwork/Rock/blob/develop/Rock.Tests/README.md) to Rock.Tests that prove my fix is effective or that my feature works
- [ ] I have included necessary documentation (if appropriate)

## Further comments

Migration files are included, `201806291811300_AddNoteAttachments.*`, but they are not included in the project itself.

I also added some `ColumnPriority` settings to the Note Type List block as it was already not displaying well on my super-wide monitor, let alone smaller monitors.

## Documentation

https://www.rockrms.com/Rock/BookContent/9/113#addingmultiplenotetypestoasingleentity will need to be updated to include a mention of the preliminary support for note attachments. I don't have much to write up on this as we aren't actually providing UI support for using attachments, so it's hard to describe the feature beyond "coming soon".

## Screenshots

2018-06-29 15_09_11-virtualbox

2018-06-29 15_08_42-virtualbox

2018-06-29 15_09_29-virtualbox

### CODE REVIEW

**Comment by edmistj** [comment]
@cabal95 Does your plugin require the UI updates for configuring the settings? It's a little confusing to have the option visible and not provide core support for it.

**Comment by edmistj** [comment]
I think adding Visible = false is good. Thanks for the good work!

**Comment by cabal95** [comment]
I'll get the extra commit done tomorrow and verify that `.Visible=false` keeps everything clean.

**Comment by cabal95** [comment]
Should be all set now!

**Comment by cabal95** [comment]
Okay, it should _really really_ be all set now. 🤦‍♂️ on missing DbSet.

**Comment by nairdo** [comment]
Now, please give me a few minutes to officially add the corresponding migration to the project and test it.  It should be ready in 15 minutes or so.

**Comment by nairdo** [comment]
@DerekMangrum  Oops, I had to revert this for now since we're in a migration freeze which I forgot about.  I'll redo once I get the all clear on the freeze.

**Comment by nairdo** [comment]
@cabal95 I had to recreate the commit from pieces.  It's now been committed to the `develop` branch via https://github.com/SparkDevNetwork/Rock/commit/9a98b8f7675bcfc70dfdc5e14fd9bc71696f0a7a.

**Pull request merged**
