### PR TITLE
Move metric creation (Fixes #5079)

### LINKED ISSUE #5079: Attributes don't save when creating a new Metric
#### A Picture Is worth a Thousand Words

Screen Shot 2022-07-19 at 3 43 29 PM

### Description

When creating a brand new Metric, attribute values do not save. The Metric gets saved with all the information except for its attributes that were thought to be assigned. A person has to edit the now existing metric to add the attribute values.

### Steps to Reproduce

1. Ensure that the Metric Entity Type has attributes. It does not matter what kind.
2. Go to create a new Metric.
3. Add an attribute value to the Metric's attributes.
4. Click "Save". (The Attribute Value should not have saved)
5. Click "Edit" to add the Attribute Value to the now existing Metric.
6. Click "Save" to finally add the Attribute Value.

**Expected behavior:**
Attribute values to be added to the new Metric on creation.

**Actual behavior:**
The new Metric is created without any attribute values assigned.

Rock Version: [12.8, 13.6]
Client Culture Setting: [en-US]

### PR DESCRIPTION
**Pull request by nlBayside**
Moves metric creation to occur sooner, so that the attribute values have something to be added to in the database.

## Notice

**We cannot guarantee that your pull request will be accepted.**  There are many factors involved.  We take into consideration whether or not the Rock system you run is a standard, main-line build.  If it is not, there is a lower chance we will accept your request (since it may impact a part of the system you don't regularly use).  Features that would be used by less than 80% of Rock organizations, or ones that don't match the goals of Rock, are other important factors.

## Proposed Changes
Move Lines 507-513 further up in the MetricDetail Block code, so that the attribute values are assigned a proper EntityId on creation.

Fixes: #5079

## Types of changes

What types of changes does your code introduce to Rock?
_Put an `x` in the boxes that apply_

- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality, which has been approved by the core team)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [X] This is a single-commit PR. (If not, please squash your commit and re-submit it.)
- [X] I verified my PR does not include whitespace/formatting changes -- because if it does it will be closed without merging.	
- [X] I have read the [Contributing to Rock](https://github.com/SparkDevNetwork/Rock/blob/master/.github/CONTRIBUTING.md) doc
- [X] By contributing code, I agree to license my contribution under the [Rock Community License Agreement](https://www.rockrms.com/license)
- [ ] Unit tests pass locally with my changes
- [ ] I have added any required [unit tests](https://github.com/SparkDevNetwork/Rock/blob/develop/Rock.Tests.UnitTests/README.md) or [integration tests](https://github.com/SparkDevNetwork/Rock/blob/develop/Rock.Tests.Integration/README.md) that prove my fix is effective or that my feature works
- [ ] I have included updated language for the [Rock Documentation](https://www.rockrms.com/Learn/Documentation) (if appropriate)

## Documentation
N/A

## Migrations
N/A

### CODE REVIEW

**Comment by nairdo** [comment]
Hi @nlBayside , I looked at your change and it might be better if this `...GetEditValues( metric )` and its `SaveAttributeValues()` was moved to _after_ the `if ( metric.Id == 0 ) ... metricService.Add( metric )` block instead of moving _that_ save higher like you did.   So more like this:

```CSharp
    if ( metric.Id == 0 )
    {
        metricService.Add( metric );

        // save to make sure we have a metricId
        rockContext.SaveChanges();
    }

    // **Now we can safely save the attribute values**

    avcEditAttributeValues.GetEditValues( metric );

    // only save if everything saves:
    rockContext.WrapTransaction( () =>
    {
        rockContext.SaveChanges();
        metric.SaveAttributeValues();
    } );
```

I know the it's been like this since the [b41ccbc](https://github.com/SparkDevNetwork/Rock/pull/4095/commits/b41ccbc33161f7b20e5437113ba5db1e69f5d255#diff-af6f33ec1edbe427f4ac491f224ff8b2debb0e0a51cc292bbde395467b6118d2R279-R285) commit that added the feature, but looking at _that_ commit again I see there is [some validation](https://github.com/SparkDevNetwork/Rock/blob/d7f4a0fdbb8195b3f4330cdb902a4f7341416f56/RockWeb/Blocks/Reporting/MetricDetail.ascx.cs#L439) that occurs before the `scheduleService.Add( schedule );`  and its `rockContext.SaveChanges();` so it would be best to only save the metric _after_ it passes validation.

Let me know if you're not comfortable adjusting / squashing your commit and we can do it over here (but then you would not get the Github merge credit.)

**Comment by nlBayside** [comment]
Yes, that was once concern I had after creating the commit. I can definitely make adjustments to the change reflecting what you suggested. I'll get that done when I have a chance too soon. Thank you!

**Comment by nlBayside** [comment]
Hello! I submitted this update to the PR almost a week ago and I'm not sure what the next steps are for Rock. I did notice this page in the Github wiki: [Contributing to Rock](https://github.com/SparkDevNetwork/Rock/wiki/Contributing-to-Rock#how-can-i-contribute).
It sounds like there's a CLA that someone outside of Spark Development would need to sign. If that's the case still, I'm more than happy to cooperate with your team's internal processes! I haven't filled out the form previously. Thank you!

**Comment by nairdo** [comment]
Thanks @nlBayside We typically get to pull requests depending on our workload.  As far as signing a the [Spark Contributor Agreement](http://www.rockrms.com/Content/RockExternal/Misc/Contributor%20Agreement.pdf), that's always a good idea --but submitting a Pull Request here means you've agreed to the terms.  (Since that secretary @ sparkdevnetwork.org email does not appear to be working at the moment, you can email it to nick @ spark... once you sign it.)

Lastly, are you open to including your name on your messages here?  (Since [your profile](https://github.com/nlBayside) is a bit sparse it would be nice to know who we're talking with -- although I'm pretty sure your name is Noah, right?)

**Pull request merged**
