### PR TITLE
SaveAttributeValues() now loads and saves once

### PR DESCRIPTION
**Pull request by chrismcgrath**
# Contributor Agreement
_Have you filled out and sent your [Spark Contributor Agreement](http://www.rockrms.com/Content/RockExternal/Misc/Contributor%20Agreement.pdf) to secretary [at] sparkdevnetwork.org?_

Yes

# Context
_What is the problem you encountered that lead to you creating this pull request?_

We have about 200 person attributes. Calling SaveAttributeValues() takes a few seconds to run because it loops through all the attributes and loads their values one at a time, then saves each modified attribute one at a time.

# Goal
_What will this pull request achieve and how will this fix the problem?_

To optimize the process of saving all attributes.

# Strategy
_How have you implemented your solution?_

Instead of calling SaveAttributeValue() for each attribute, instead load all the entity's attributes all at once, update all that need updating, then save once at the end.

# Possible Implications
_What could this change potentially impact? Are there any security considerations? Where could this potentially affect backwards compatibility?_

# Screenshots
_Provide us some screenshots if your pull request either alters existing UI or provides new UI. Arrows and labels are helpful._

# Documentation
_If your change effects the UI or needs to be documented in one of the existing [user guides](http://www.rockrms.com/Learn/Documentation), please provide the brief write-up here:_

### CODE REVIEW

**Comment by chrismcgrath** [comment]
Found a bug, working on fixing it.

**Comment by chrismcgrath** [comment]
OK, Found another issue. Current code is not taking into account the EntityTypeQualifierColumn and EntityTypeQualifierValue when pulling attributes for things like Workflow Actions.  It may be time to drop this if I don't find an easy solution to loading the proper attributes for any IHasAttributes object. Suggestions are welcome but feel free to reject this pull request if this isn't a good path.

**Comment by nairdo** [comment]
@chrismcgrath I think it would be great if you figured out how to make this work with only one SaveChanges() call!  I don't have any suggestions at this point.  It could have a huge impact on various parts of Rock that call the SaveAttributeValues(...) method.  I'll close this for now, but please do resubmit if you figure it out.

**Comment by chrismcgrath** [comment]
@nairdo maybe I'm confused but it looks like there is only one SaveChanges call to me, that was my intent. The save happens outside the for loop. Am I missing something?

Get Outlook for Android<https://aka.ms/ghei36>




On Fri, Mar 3, 2017 at 5:40 PM -0600, "Nick Airdo" <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #2025<https://github.com/SparkDevNetwork/Rock/pull/2025>.

**Comment by chrismcgrath** [comment]
Nick saw my last comment and thought I hadn't figured this out, but I did a commit afterward that did get it working properly. Worth reviewing. Thanks!

**Pull request merged**
