### PR TITLE
Added Workflows to Financial Batch List

### PR DESCRIPTION
**Pull request by tscrip**
## Proposed Changes
There are several times where we want to be able to take action on a certain collection of Batches. 

This change to the Financial Batch List block adds the ability to specify Workflows in the Block Settings. After workflows have been specified, buttons for said workflows are rendered on the footer of the Grid. Upon clicking the button, the selected batches are passed to the workflow in the form of an Text Attribute called Batches.

Ideally, you would created a workflow that loops through the comma separated list of BatchIds, and generate your content IE: Send an email about certain batches, generate an export for your GL, or just mark certain batches as closed.

**UPDATE**
Here are a few screenshots.

This is a screenshot of the Block Settings. This is where you select what workflows you want available.
image

This is the screenshot of the buttons being displayed on the Batch List Action bar. Note that it is pulling the icon from the workflow.
image

This screenshot is screenshot of the attribute that will be populated. It is expecting a comma separated list of BatchIds.
image

## Types of changes

What types of changes does your code introduce to Rock?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality, which has been approved by the core team)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [X] I verified my PR does not include whitespace/formatting changes -- because if it does it will be closed without merging.	
- [X] I have read the [Contributing to Rock](https://github.com/SparkDevNetwork/Rock/blob/master/.github/CONTRIBUTING.md) doc
- [X] By contributing code, I agree to license my contribution under the [Rock Community License Agreement](https://www.rockrms.com/license)
- [ ] Unit tests pass locally with my changes
- [ ] I have added [required tests](https://github.com/SparkDevNetwork/Rock/blob/develop/Rock.Tests/README.md) that prove my fix is effective or that my feature works
- [ ] I have included updated language for the [Rock Documentation](https://www.rockrms.com/Learn/Documentation) (if appropriate)

### CODE REVIEW

**Comment by edmistj** [comment]
@tscrip Could you add some screenshots of the changes?

**Comment by tscrip** [comment]
@edmistj Sure. I just attached a few screenshots above.

**Comment by edmistj** [comment]
@tscrip hum not seeing them.

**Comment by edmistj** [comment]
Also can you give some use cases of what these workflows might do?

**Comment by tscrip** [comment]
@edmistj I can confirm they were attached above this time (I was creating a comment and updating the Issue last time. I guess one of them didn't get saved). 

As far as use cases, these are a few use cases I can come up with right now.

- Export Batch to Accounting System (GL Export)
- Nudge a fellow accountant to take a look at a batch
- Specifically for Shelby V5, it might be cool to be able to bulk update the Project Code in a Batch.
- Close a collection of batches (Ghetto Bulk Update)

**Comment by edmistj** [comment]
These use cases would require additional workflow actions to work though right? (or the dreaded (complex) SQL action)

**Comment by tscrip** [comment]
Potentially yes. One thing I was kicking around was creating a Field Type for Financial Batch. That way, you could just pass a comma separated list of Guids and have the Batches already in context in the workflow. That way, you could just do something like:
```
{% assign batches = Workflow | Attribute:'FinancialBatches', 'Object' %}
{% assign rows = '' %}
{% for batch in batches %}
    {% assign glAccountNumber = batch | Attribute:'GLAccount' %}
    {% assign glSomething = batch | Attribute:'GLSomething' %}
    {% capture rows %}{{ rows }}\r\n{{glAccountNumber}},{{glSomething}}{% endcapture %}
{% endfor %}

{{ rows }}
```

At this point, I will take the SQL over managing a duplicate core block with added features.

**Comment by nairdo** [comment]
Thank you Tyler.  We reviewed this in more detail yesterday and decided to take a pass on this one for now.  It's a bit too far outside the complexity and pattern we're establishing for core block functionality. Even though we won't be pulling this into core, we are always grateful for the ideas and contributions to Rock.

**Pull request closed without merging**
