### PR TITLE
+ Fixed issue where urls were generated with http even though site is loaded over https.

### PR DESCRIPTION
**Pull request by paperreduction**
## Proposed Changes

Fixes: #4115 

Updated ResolveRockUrlIncludeRoot to use https if WebRequestHelper.IsSecureConnection() returns true, otherwise uses previous behavior. 

## Types of changes

What types of changes does your code introduce to Rock?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality, which has been approved by the core team)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] This is a single-commit PR. (If not, please squash your commit and re-submit it.)
- [x] I verified my PR does not include whitespace/formatting changes -- because if it does it will be closed without merging.	
- [x] I have read the [Contributing to Rock](https://github.com/SparkDevNetwork/Rock/blob/master/.github/CONTRIBUTING.md) doc
- [x] By contributing code, I agree to license my contribution under the [Rock Community License Agreement](https://www.rockrms.com/license)
- [ ] Unit tests pass locally with my changes
- [ ] I have added [required tests](https://github.com/SparkDevNetwork/Rock/blob/develop/Rock.Tests/README.md) that prove my fix is effective or that my feature works
- [ ] I have included updated language for the [Rock Documentation](https://www.rockrms.com/Learn/Documentation) (if appropriate)

## Further comments

I'm a python developer that uses mac/linux. I setup a windows machine and installed VS just to track down this issue today. Can't get the project to build (VS fails, but then shows 0 errors).

Would love to add/run test for this, but I also have no idea how to do that yet.

Submitting this PR regardless, hoping I'll get the project running shortly.

## Documentation

N/A

## Migrations

N/A

### CODE REVIEW

**Comment by jasonhendee** [comment]
@paperreduction , Can you please verify how you discovered this issue? Do you run Rock behind a load balancer or proxy by chance? Thank you.

**Comment by paperreduction** [comment]
@jasonhendee We do run rock behind a proxy, which handles SSL termination and then calls IIS on port 80. Proxy sends the request with X-Forwarded-Proto set if the request originally came in as https.

Generally most things in rock seem to work fine, but we found that when processing payments  the GatewayStep2Return.aspx address that was being used was generated as http. This was causing a redirect from https to http and raising an error in chrome.

I believe you can see that address being generated RockWeb > Blocks > Finance > TransactionEntry.ascx.cs. But there are a few other blocks that also can be used for payment. And all of them seem to use the ResolveRockUrlIncludeRoot() method.

Let me know if there is anything else you need.

**Comment by paperreduction** [comment]
@jasonhendee Also, is this patch going out to both 9 and 10, or just 10? I couldn't find your support policy.

**Comment by jasonhendee** [comment]
> We do run rock behind a proxy

Thank you for confirming and pointing out specific examples. I was able to recreate the issue on my end.

> Also, is this patch going out to both 9 and 10, or just 10?

I will verify this and get back with you. Thanks!

**Comment by jasonhendee** [comment]
@paperreduction , to follow-up with your question:

**Comment by jasonhendee** [comment]
@paperreduction , to follow-up with your question:

> is this patch going out to both 9 and 10, or just 10?

This PR will be merged into the develop branch, which means it will be going directly into v11. We will also merge the fix into versions 10.3 and 9.5.

May I ask what organization you're representing and what version of Rock you're currently running? Thanks again for taking the time to contribute!

**Comment by paperreduction** [comment]
@jasonhendee Grace Church (gracechurchsc.org) and we're currently on 9. The 9 database schema is compatible with the import tool we're using to migrate. Once we move all our data we're going to be working on updating, but no ETA on that yet.

Thanks for the quick turn around on this, much appreciated.

**Pull request merged**
