### PR TITLE
Added embedding videos in email

### PR DESCRIPTION
**Pull request by trydyingtolive**
## Proposed Changes
Our staff wanted a way to embed videos in email as they had previously done in MailChimp. This PR allows folks to link to a Vimeo or YouTube video and have a thumbnail automatically added.

## Types of changes

What types of changes does your code introduce to Rock?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality, which has been approved by the core team)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] I verified my PR does not include whitespace/formatting changes -- because if it does it will be closed without merging.	
- [x] I have read the [Contributing to Rock](https://github.com/SparkDevNetwork/Rock/blob/master/.github/CONTRIBUTING.md) doc
- [x] By contributing code, I agree to license my contribution under the [Rock Community License Agreement](https://www.rockrms.com/license)
- [x] Unit tests pass locally with my changes
- [ ] I have added [required tests](https://github.com/SparkDevNetwork/Rock/blob/develop/Rock.Tests/README.md) that prove my fix is effective or that my feature works
- [ ] I have included updated language for the [Rock Documentation](https://www.rockrms.com/Learn/Documentation) (if appropriate)

## Further comments
I created a new VideoEmbedComponent so that plugins can extend functionality. This PR only includes Vimeo and YouTube since they are the most common for our needs. This also allows you to switch out your thumbnail if you want (though at that point you might as well use an image).

image

image

image

image

-----
Assigned to DavidT for QA Testing

### CODE REVIEW

**Comment by cabal95** [comment]
Not sure how the underlying logic is written, but when uploading your own preview image, would it make sense to automatically overlay a play button in the center?

This would of course mean we would need to modify the image on upload.

Or maybe a button they can click that will add a "play button" overlay to the current image?

**Comment by trydyingtolive** [comment]
@cabal95 I thought about that. Even as far as should there be a way to swap out play buttons or turn them off all together? In the end I opted to copy MailChimp's functionality and keep it simple. Though if we wanted to break apart the thumbnail getting from the play button adding this would be the time. That way we could expand functionality and avoid breaking backward comparability in the future.

**Comment by edmistj** [comment]
I'd worry too that we'd never be able to please anyone. Someone would want the arrow in red, etc.

**Comment by mcnoodles** [comment]
We would love to see Wistia added if at all possible.

**Comment by sparkdevnetwork-service** [comment]
➤ grace hansen commented:

Nick Airdo ( https://app.asana.com/0/21779865363458/list ) - Label is PR ready - 4/5

**Comment by sparkdevnetwork-service** [comment]
➤ Nick Airdo commented:

Hi grace hansen ( https://app.asana.com/0/958164134519812/list ) I've looked this one over and it looks mostly solid (it will need some minor cleanup).  It should now be tested thoroughly and then it should be assigned to Mike for integration (PR merging) since it involves some items that Mike is best suited to handle.

**Comment by nairdo** [comment]
Hi Mark @trydyingtolive We're planning to do a PR fest in a few weeks, and would really love it if you could please re-submit this PR with all commits squashed into one.  Thanks in advance!!

**Comment by azturner** [comment]
@nairdo, Tested this and it's working great. I did need to update the Public Application Root global attribute setting to be correct for the thumbnails to appear correctly when entering the YouTube and Vimeo url values.

**Comment by jonedmiston** [comment]
Update: Working on this for inclusion in a v12.x. Will push to hotfix branch soon.

**Pull request merged**
