### PR TITLE
Created VS 2013 export

### PR DESCRIPTION
**Pull request by arranf**
Based on settings outlined at https://github.com/SparkDevNetwork/Rock/wiki/Coding-standards

### CODE REVIEW

**Comment by arranf** [comment]
This is related to #691

**Comment by azturner** [comment]
@arranf , Thanks for creating this. Can you also follow [these guidelines](https://github.com/SparkDevNetwork/Rock/wiki/Committing-Your-Code) when making commits. Thanks,
-David

**Comment by arranf** [comment]
@azturner Would it be possible to feature that more prominently somewhere
in the Dev docs or perhaps on the Wiki landing page? I wasn't aware they
existed but I'll bookmark them now.

**Comment by nairdo** [comment]
@arranf those things are (were) essentially for developers committing their code to the core (develop branch) but the Rock dev docs are not intended to cover that scenario.  For now, keep this wiki page as your [Core Developer guidelines](https://github.com/SparkDevNetwork/Rock/wiki/z.-Core-Team-Developers) reference.

**Pull request merged**
