### PR TITLE
Fundraising Donation Entry Base Group

### LINKED ISSUE #2982: [EN] Fundraising Donation Entry - Filter Fundraising Groups
Before completing your first issue we highly recommend reading this post on [Effective Ways To Get Help from Maintainers](https://www.snoyman.com/blog/2017/10/effective-ways-help-from-maintainers).

### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description
Add a new block property that will allow the administrator/webmaster select a base group for the fundraising donation entry group dropdown.  This will allow for the creation of multiple instances of the block type so that you could potentially brand or target different groups.

### Steps to Reproduce

1. Load the Fundraising Donation Entry Block without providing an individual group
2. The group drop down will show all active fundraising groups that have people in the group.

**Expected behavior:** 

With new feature only the selected group and it's child groups who have members in the group will show in drop down list

**Actual behavior:** 

All active fundraising groups with with members will show in drop down list

### Versions

* **Rock Version:** 7.3
* **Client Culture Setting:** en-us

### PR DESCRIPTION
**Pull request by chrisfunk**
Added logic to set base/root group for the Fundraising Donation Entry…Block.  Resolves #2982

# Rock PR Policy
The Rock Community loves Pull Requests! In an effort to 'row in the same direction' and minimize wasted development time
on your part and review time on ours, we have implemented the following guidelines for PRs:
1. If you are submitting a PR for a logged Issue / Enhancement request please reference it in your commit
2. If your PR is for an enhancement that has not been discussed and approved by the core team please get that approval BEFORE submitting
the request. In fact, this approval should be received before writing the code to limit rework on your part. This will ensure that all code is working into the same vision and direction of the core project.

## Contributor Agreement
_By contributing your code, you agree to license your contribution under the [Rock Community License Agreement](https://www.rockrms.com/license)._

## Context
We needed the ability to only show a specific set of fundraising groups on the fundraising donation entry block, and we did not have a way to filter the group list prior to implementing this block setting and associated features.

## Goal
It will allow us to set a base/root group to only show that group and any potential child groups.

## Strategy
1.  Added a "Base Group" Group picker to the block settings.
2. When loading the group drop down, the block will check to see if the base group has been configured in the block settings, if so it will use a SQL query to retrieve a list of child groupIds that are below the selected group.
3. The resulting group ids are used as an additional filter to only show groups that are part of the list from step 2.

## Tests
_If your code is a new method or function (that doesn't need a mock database or SqlServerTypes library) and can be Xunit tested [see example](https://github.com/SparkDevNetwork/Rock/blob/develop/Rock.Tests/Rock/Lava/RockFiltersTests.cs) be sure your pull request includes the corresponding unit tests in the Rock.Tests project. In all cases *you* MUST test your code before submitting a pull request._

## Possible Implications
_What could this change potentially impact? Are there any security considerations? Where could this potentially affect backwards compatibility?_

## Screenshots
_Provide us some screenshots if your pull request either alters existing UI or provides new UI. Arrows and labels are helpful._

## Documentation
_If your change effects the UI or needs to be documented in one of the existing [user guides](http://www.rockrms.com/Learn/Documentation), please provide the brief write-up here:_

## Migrations
Should your pull request require a migration, please exclude the migration from the Rock.Migration project, but submit it in your pull request. Please add a note to your pull request that provides a heads up that a migration file is present.

### CODE REVIEW

**Comment by MikeDPeterson** [comment]
@chrisfunk We have a GetAllDescendents() method on our GroupService that you can use instead of the raw sql. See https://github.com/SparkDevNetwork/Rock/blob/680af1db76d7e5ef7a4e52fcffeb28020ac73d60/Rock/Model/GroupService.Partial.cs#L1

**Comment by chrisfunk** [comment]
Thanks Mike. I forgot about that. I will make an update

**Comment by chrisfunk** [comment]
@MikeDPeterson Updated pull request to include your recommendation.

**Comment by MikeDPeterson** [comment]
@chrisfunk looks good! Thanks!

**Pull request merged**
