### PR TITLE
Fixed animated gifs being turned into static gifs

### PR DESCRIPTION
**Pull request by trydyingtolive**
## Proposed Changes
Putting animated Gifs in your email to drive engagement is apparently the new hotness. We tried this and it didn't work. Turns out GetImage.ashx is sending images on to the resizer even when didn't ask it to, and this breaks the animation.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality, which has been approved by the core team)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] I verified my PR does not include whitespace/formatting changes -- because if it does it will be closed without merging.	
- [x] I have read the [Contributing to Rock](https://github.com/SparkDevNetwork/Rock/blob/master/.github/CONTRIBUTING.md) doc
- [x] By contributing code, I agree to license my contribution under the [Rock Community License Agreement](https://www.rockrms.com/license)
- [x] Unit tests pass locally with my changes
- [ ] I have added [required tests](https://github.com/SparkDevNetwork/Rock/blob/develop/Rock.Tests/README.md) that prove my fix is effective or that my feature works
- [ ] I have included updated language for the [Rock Documentation](https://www.rockrms.com/Learn/Documentation) (if appropriate)

## Further comments
I added a method that adds up all of the query parameters we know aren't for Image Resizer and uses that to check to see if we need to get the image resized. This is similar to what was being done before just more thorough.

### CODE REVIEW

**Comment by nairdo** [comment]
@trydyingtolive Hi Mark.  What are your about this -- never allow resizing if it's an animated gif?  Do you think you'll have cases where someone _would_ want their animated gif to be resized (broken, non-animated)?

```csharp
private Stream GetResized( NameValueCollection queryString, Stream fileContent, string mimeType )
{
    try
    {
        if ( mimeType == "image/gif" )
        {
            var i = Image.FromStream( fileContent );
            var FrameDimensions = new System.Drawing.Imaging.FrameDimension( i.FrameDimensionsList[0] );
            var frames = i.GetFrameCount( FrameDimensions );
            // Don't resize animated GIFs
            if ( frames > 1 )
            {
                return fileContent;
            }
        }
...
```

**Comment by trydyingtolive** [comment]
@nairdo I can't imagine ever wanting to resize an animated gif in a way that breaks it. I think bypassing ImageResizer when not needed is nice. Though the images are being cached, so maybe it's not that big of a pick up.

**Comment by nairdo** [comment]
@trydyingtolive After a brief discussion here, we're going to go with your original idea as it should be more performant.

**Comment by sparkdevnetwork-service** [comment]
➤ grace hansen commented:

Nick Airdo ( https://app.asana.com/0/21779865363458/list ) - Label is PR Ready - 4/5

**Pull request merged**
