### PR TITLE
Fixed incorrect attendance counts plus minor speed improvement spCheckin_BadgeAttendance (Fixes #3547)

### LINKED ISSUE #3547: Family Attendance Badge Show Incorrect Count
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description
When viewing the Family Attendance badge, you will notice that the data is a little off. After digging into the code, I found that it is using a REST API: `/api/PersonBadges/FamilyAttendance/` which is calling a Stored Procedure: `spCheckin_BadgeAttendance`

Looking at the code in the Stored Procedure, it appears to be giving someone credit if the group met. It doesn't look like it is checking to see if the `DidAttend` bit is flipped.

I think the fix is going to be updating the following line in the stored procedure above.
**Stored Procedure**: `spCheckin_BadgeAttendance`
**Line Number**: 94
`INNER JOIN [AttendanceOccurrence] O ON O.[Id] = A.[OccurrenceId]`
to
`INNER JOIN [AttendanceOccurrence] O ON O.[Id] = A.[OccurrenceId] AND A.[DidAttend] = 1`

### Steps to Reproduce

1. Add a person to a group
2. Add an attendance record for the group (but don't add attendance for person)
3. Run the stored procedure and notice they are getting credit

**Expected behavior:**
They should not be given credit for any group they are a member of. The stored procedure needs to be updated to look for attendance records with the `DidAttend = 1` flag.

**Actual behavior:**
Stored Procedure is looking at Group Attendance. If the group met, all group members are getting credit.

### Versions

* **Rock Version:** 8.5
* **Client Culture Setting:** en-US

### PR DESCRIPTION
**Pull request by tom-powers**
## Proposed Changes

Take 2 - I did not create bugfix branch first, so our develop branch in secc/Rock got messed up.  Recreating pull request to fix all of this.

We noticed that the family attendance chart was rendering slowly for adults - 8 to 10 seconds. I rewrote spCheckin_BadgeAttendance sproc (based on v1.8.4) before noticing that Joseph Dixon had already updated this sproc in v1.8.5. Joseph's changes were indeed faster, but the output wasn't always consistent with previous versions of the sproc (i.e. in some months, the attendance counts were higher than expected). I looked at the underlying data to verify that the counts were in fact too high.

Fixes: #3547

## Types of changes

What types of changes does your code introduce to Rock?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality, which has been approved by the core team)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I verified my PR does not include whitespace/formatting changes -- because if it does it will be closed without merging.	
- [x] I have read the [Contributing to Rock](https://github.com/SparkDevNetwork/Rock/blob/master/.github/CONTRIBUTING.md) doc
- [x] By contributing code, I agree to license my contribution under the [Rock Community License Agreement](https://www.rockrms.com/license)
- [x] Unit tests pass locally with my changes
- [ ] I have added [required tests](https://github.com/SparkDevNetwork/Rock/blob/develop/Rock.Tests/README.md) that prove my fix is effective or that my feature works
- [ ] I have included updated language for the [Rock Documentation](https://www.rockrms.com/Learn/Documentation) (if appropriate)

## Further comments
Looked at many performance benchmarks - here are the most recent numbers for an adult in the family on our development server (not as beefy as our production server):

* right after clearing procedure cache and cleaning buffers
  SQL Server Execution Times:
  CPU time = 157 ms,  elapsed time = 1113 ms.
* after procedure is cached
  SQL Server Execution Times:
  CPU time = 0 ms,  elapsed time = 9 ms.

We were seeing 8000-9000 milliseconds before optimizations

## Documentation
none

### CODE REVIEW

**Comment by nairdo** [comment]
Thanks @tom-powers By any chance have you tried running this on a SQL Server 2012 db?  I've got an environment (with fairly real data) and for some reason the query takes over 2 minutes to complete.  (_From my basic analysis, it seems like the LEFT OUTER JOIN with that ufnUtility_GetSundaysBetweenDates CTE appears to be the culprit._)

**Comment by tom-powers** [comment]
@nairdo I didn't try on SQL 2012 but I'll do that now.  I'll let you know what I uncover.

**Comment by nairdo** [comment]
@tom-powers, also interestingly, I just discovered if I change this one line: https://github.com/SparkDevNetwork/Rock/blob/79aa033df797b1d96b0fe0d5cd0dd5c3a71753a1/database/Procedures/spCheckin_BadgeAttendance.sql#L87

From  `s.[SundayDate], a.[Attended]` to `s.[SundayDate], 1 as [Attended]` it works and runs in 22ms.

**Comment by nairdo** [comment]
Would this UNION accomplish the same thing as that LEFT OUTER JOIN?

```Sql
-- query for attendance data
SELECT 
	COUNT(b.[Attended]) AS [AttendanceCount]
	, (SELECT dbo.ufnUtility_GetNumberOfSundaysInMonth(DATEPART(year, b.[SundayDate]), DATEPART(month, b.[SundayDate]), 'True' )) AS [SundaysInMonth]
	, DATEPART(month, b.[SundayDate]) AS [Month]
	, DATEPART(year, b.[SundayDate]) AS [Year]
FROM (
	SELECT
		s.[SundayDate], NULL as [Attended]
	FROM
		dbo.ufnUtility_GetSundaysBetweenDates(@StartDay, @LastDay) s
	UNION
			SELECT
				DISTINCT ao.[SundayDate], 1 as [Attended]
			FROM
				[AttendanceOccurrence] ao WITH(NOLOCK)
				INNER JOIN (SELECT [Id] FROM [dbo].[ufnCheckin_WeeklyServiceGroups]()) wg ON ao.[GroupId] = wg.[Id]
				INNER JOIN [Attendance] a WITH(NOLOCK) ON ao.[Id] = a.[OccurrenceId] AND a.[DidAttend] = 1
				INNER JOIN [PersonAlias] pa WITH(NOLOCK) ON a.[PersonAliasId] = pa.[Id] AND pa.[PersonId] IN (SELECT [PersonId] FROM @familyMemberPersonIds)
			WHERE
				ao.[OccurrenceDate] BETWEEN @StartDay AND @LastDay
			
) b
GROUP BY DATEPART(month, b.[SundayDate]), DATEPART(year, b.[SundayDate])
OPTION (MAXRECURSION 1000)
```

**Comment by tom-powers** [comment]
@nairdo makes sense to me.  I would change the UNION to UNION ALL though since the two datasets are mutually exclusive, and it will give a performance bump.  Also, I just saw one more thing that can be simplified that I didn't catch the first time around:

INNER JOIN (SELECT [Id] FROM [dbo].[ufnCheckin_WeeklyServiceGroups]()) wg ON ao.[GroupId] = wg.[Id]

      can be changed  to

INNER JOIN [dbo].[ufnCheckin_WeeklyServiceGroups]() wg ON ao.[GroupId] = wg.[Id]

good catch on all of this - are you going to modify the pull request or do you want me to do it?

**Comment by nairdo** [comment]
@tom-powers If you have any time to complete/test this in your environment -- I'd be grateful.  If not, let me know.

**Comment by tom-powers** [comment]
@nairdo, took me a while to get a SQL 2012 instance spun up with my data.  For me, the most recent commit is extremely performant in both SQL 2012 and SQL 2016.  Ready for your eyes.

**Comment by edmistj** [comment]
@tom-powers thanks so much for all the effort!

**Pull request merged**
