### PR TITLE
Add TransactionType to PaymentInfo to Make Type Accessible to Gateways

### PR DESCRIPTION
**Pull request by arranf**
## Context
#2433 

## Goal
To make the type of transaction available to gateways

## Strategy
I've added a `int? TransactionTypeId` property to the base `PaymentInfo` class. I've also added code in each block that I could find that creates transactions to populate it.

## Possible Implications
This should be backwards compatible.

### CODE REVIEW

**Comment by mcnoodles** [comment]
This would help us tremendously!  Thanks Aaran!

**Comment by taylorbrooks** [comment]
womp womp

**Comment by nairdo** [comment]
@taylorbrooks No... We've had another incident with the sync tool (Unito) we use.  We recently separated our Issues and Pull requests into two syncs and it overreacted.  I'm doing cleanup now. :(

**Comment by MikeDPeterson** [comment]
Merged locally with https://github.com/sparkdevnetwork/rock/commit/e8340eaeafe9387a69c1be8d92c8b3490c162ba2

**Pull request closed without merging**
