### PR TITLE
Add Age to BirthDate column in Event Registrant lists

### PR DESCRIPTION
**Pull request by cabal95**
## Contributor Agreement
_By contributing your code, you agree to license your contribution under the [Rock Community License Agreement](https://www.rockrms.com/license)._

## Context
_What is the problem you encountered that lead to you creating this pull request?_

Staff needs ability to know age of person registered for an event when looking at the list of registrants as well as when placing in groups.

See #2763.

## Goal
_What will this pull request achieve and how will this fix the problem?_

Display age along with Birth Date.

## Strategy
_How have you implemented your solution?_

I gave my cat a Red Bull, set her up on my desk and walked away for 42 minutes. When I came back she was passed out but had completed the code changes necessary.

Rock.Web.UI.Controls.DateField has new property of `IncludeAge` which will append the age of the person to the birth date when displayed. This property is enabled when used in the Registration Instance Details block.

If 18 months old or younger it displays as `(## mo)`, if older then it displays as `(## yo)`.

## Tests
_If your code is a new method or function (that doesn't need a mock database or SqlServerTypes library) and can be Xunit tested [see example](https://github.com/SparkDevNetwork/Rock/blob/develop/Rock.Tests/Rock/Lava/RockFiltersTests.cs) be sure your pull request includes the corresponding unit tests in the Rock.Tests project. In all cases *you* MUST test your code before submitting a pull request._

## Possible Implications
_What could this change potentially impact? Are there any security considerations? Where could this potentially affect backwards compatibility?_

I may have to take my cat to the vet if she doesn't wake up.

## Screenshots
_Provide us some screenshots if your pull request either alters existing UI or provides new UI. Arrows and labels are helpful._

2018-02-13 16_12_24-virtualbox

2018-02-13 16_15_25-virtualbox

## Documentation
_If your change effects the UI or needs to be documented in one of the existing [user guides](http://www.rockrms.com/Learn/Documentation), please provide the brief write-up here:_

## Migrations
Should your pull request require a migration, please exclude the migration from the Rock.Migration project, but submit it in your pull request. Please add a note to your pull request that provides a heads up that a migration file is present.

### CODE REVIEW

**Comment by nairdo** [comment]
Just saw this now on our system.  Yo looks pretty odd.  Is "yo" the best abbreviation to use?  Can this be "yr" or "yrs", or we we must, even possibly "y/o"

**Comment by edmistj** [comment]
Think we should make this yr

**Comment by cabal95** [comment]
Do you need another PR on this or will you take care of it internally?

**Comment by edmistj** [comment]
We got it super simple.

**Pull request merged**
