### PR TITLE
Added a minimum age option to new accounts

### PR DESCRIPTION
**Pull request by trydyingtolive**
# Contributor Agreement
Yes

# Context
We cannot allow children under 13 to create an account.

# Goal
This will allow us to set a minimum age for creating a new account.

# Strategy
I used the existing birthday field to see if the person is old enough to create an account. There is a new block attribute to set the minimum age in years. If the person does not meet the required age, a warning is shown.

# Possible Implications
The default minimum age is 0 so no one should be affected.

### CODE REVIEW

**Comment by edmistj** [comment]
👍 (Internal Note) I wonder if the default should be 13 as a best practice?

**Comment by dcs619** [comment]
For context, [COPPA](https://en.wikipedia.org/wiki/Children's_Online_Privacy_Protection_Act) is the federal regulation that specifies this (and hands out fines for non-compliance).

**Comment by tom-powers** [comment]
David, I didn't realize the fine was so steep ($16K per infraction).  I think that defaulting to 13 might be wise indeed.

**Comment by trydyingtolive** [comment]
In light of this conversation, I have changed the default to 13 and added a warning to the help text.

**Pull request merged**
