### PR TITLE
Added View Profile button to Person Picker results and a profile link on the name on the Transaction Matching block.

### PR DESCRIPTION
**Pull request by chrismcgrath**
# Contributor Agreement
_Have you filled out and sent your [Spark Contributor Agreement](http://www.rockrms.com/Content/RockExternal/Misc/Contributor%20Agreement.pdf) to secretary [at] sparkdevnetwork.org?_

Yes

# Context
_What is the problem you encountered that lead to you creating this pull request?_

When entering or matching transactions, sometimes it's not clear whether a person with a matching name is the correct person, even after looking at the extended info that displays when selecting an individual. It can often require looking at the family, the address history, or the contribution history to determine whether this is the person the user wants.

# Goal
_What will this pull request achieve and how will this fix the problem?_

Adds links that open a profile in a new window so the user can investigate a person's information without having to search again or lose their place.

# Strategy
_How have you implemented your solution?_

Added a View Profile button to the results in the person picker. Right now it goes at the bottom because I could not figure out the styling to have it display nicely under the photo or under the member status tag.

Also added a profile link around the person name that displays on the Transaction Matching screen after a name has been selected. 

# Possible Implications
_What could this change potentially impact? Are there any security considerations? Where could this potentially affect backwards compatibility?_

None

# Screenshots
_Provide us some screenshots if your pull request either alters existing UI or provides new UI. Arrows and labels are helpful._

Person Picker:
image

Transaction Matching:
image

# Documentation
_If your change effects the UI or needs to be documented in one of the existing [user guides](http://www.rockrms.com/Learn/Documentation), please provide the brief write-up here:_

…

### CODE REVIEW

**Comment by nairdo** [comment]
Thanks @chrismcgrath we had a chance to discuss this today... can you make this an optional setting (EnableProfileLink; default false) on the PersonPicker? ( and -- it's OK if you want to hard-code the PersonPicker control declaration in the TransactionMatching block to set the flag to true.)

**Comment by nairdo** [comment]
@chrismcgrath let me know if you've had a chance to review this and if you're still interested in doing this.  To be clear, this is what we are asking for:

1. The PersonPicker would need a new EnableProfileLink property (default false) 
2. The personPicker.js would need to pass this bool along to the PeopleController's Search method.
3. The Search method would pass the bool to its private methods where your new View Profile button is added.

**Comment by chrismcgrath** [comment]
I plan on doing this, but I'll be off for the holidays and I've been and will be swamped with year-end accounting work for at least the first half of January. Sorry for the lagging!

**Comment by nairdo** [comment]
@chrismcgrath We're going to pull this in (even though it's not an optional setting on the PersonPicker user control) but Jon's going to restyle the "view profile" button to something less intrusive.

**Pull request merged**
