### PR TITLE
Update ContentChannelItemView.ascx.cs

### PR DESCRIPTION
**Pull request by treyhendon**
Add option to provide the most recent item when no query string value is provided.

## Notice

**We cannot guarantee that your pull request will be accepted.**  There are many factors involved.  We take into consideration whether or not the Rock system you run is a standard, main-line build.  If it is not, there is a lower chance we will accept your request (since it may impact a part of the system you don't regularly use).  Features that would be used by less than 80% of Rock organizations, or ones that don't match the goals of Rock, are other important factors.

## Proposed Changes

Wanted to use a single block for all sermons.  This feature accomplishes that desire.  See in action here: https://rock.hubcitychurch.com/Sermons

That page is this block.  When no `Item=` param is present, the last approved item in the Content Channel is set as the Item.

## Types of changes

What types of changes does your code introduce to Rock?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality, ~which has been approved by the core team~)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] This is a single-commit PR. (If not, please squash your commit and re-submit it.)
- [x] I have read the [Contributing to Rock](https://github.com/SparkDevNetwork/Rock/blob/master/.github/CONTRIBUTING.md) doc
- [x] By contributing code, I agree to license my contribution under the [Rock Community License Agreement](https://www.rockrms.com/license)

## Migrations
If your pull request requires a migration, please *exclude the migration from the Rock.Migration project*, but submit it with your pull request. Please add a note to your pull request that provides a heads up that a migration file is present.

### CODE REVIEW

**Comment by jonedmiston** [comment]
@treyhendon seems like this block can already do that by using the Order fields and items per page of 1. Am I missing something?

**Comment by treyhendon** [comment]
Hey @jonedmiston I think you're referring to the Content Channel View.  This is the Content Channel Item View block which logs interactions.

Unfortunately when no url param is provided, this block returns `404 - No Content. If you did not have Administrate permissions on this block, you would have gotten a real 404 page.`.

My goal for our media page was to have a single Sermons page that could start with no url param (i.e. from the nav menu click).  This block setting preserves existing functionality (404) by defaulting to false, but simply allows the added feature when set to true.

**Comment by jonedmiston** [comment]
Ah sorry @treyhendon in the future could you provide more context in the Proposed Change? There's really not much to go on there. I'm going to close this for now as it has a few issues that keep it from compiling and running. You're using attribute key and it's not declared, also your declaration of the `Description` is incorrect.

**Comment by treyhendon** [comment]
Gotcha. I'll pull down and fix.  Sorry, the attribute key was new to me - I modded in v10 and didn't notice it there, but saw in other block settings as I was pulling to develop.  I'll fix, squash and reopen this volunteer project I've done for my church.

**Pull request closed without merging**
