### PR TITLE
Allow IP configuration and Geo configuration to both function at same time

### PR DESCRIPTION
**Pull request by cabal95**
## Proposed Changes

Re-worked the logic of the check-in Admin block to still do IP-based configuration even when Geo-lookups are enabled.

Moved the Javascript snippet that handles local storage into the `.ascx` file so that it is always available as it now might be triggered on postback rather than always on initial page load.

The change to the CSS less file was so that when both the Retry and OK buttons are displayed at the same time there is some whitespace between them.

Screenshots below.

Fixes: #3259

## Types of changes

What types of changes does your code introduce to Rock?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality, which has been approved by the core team)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I verified my PR does not include whitespace/formatting changes -- because if it does it will be closed without merging.	
- [x] I have read the [Contributing to Rock](https://github.com/SparkDevNetwork/Rock/blob/master/.github/CONTRIBUTING.md) doc
- [x] By contributing code, I agree to license my contribution under the [Rock Community License Agreement](https://www.rockrms.com/license)
- [x] Unit tests pass locally with my changes
- [ ] I have added [required tests](https://github.com/SparkDevNetwork/Rock/blob/develop/Rock.Tests/README.md) that prove my fix is effective or that my feature works
- [ ] I have included updated language for the [Rock Documentation](https://www.rockrms.com/Learn/Documentation) (if appropriate)

## Further comments

Screenshots were taken on my PC, so layout might be ever so slightly different than an iPad would look.

### Manual Configuration Enabled, Geo Lookup Disabled, No IP Match

Manual=Yes Geo=No NoMatch

### Manual Configuration Enabled, Geo Lookup Enabled, User Denies GEO lookup

Manual=Yes Geo=Yes UserDenied

### Manual Configuration Enabled, Geo Lookup Enabled, No GEO Match

Manual=Yes Geo=Yes NoMatch

### Manual Configuration Disabled, Geo Lookup Enabled, No GEO Match

Manual=No Geo=Yes NoMatch

### Manual Configuration Disabled, Geo Lookup Disabled, No IP Match

Manual=No Geo=No NoMatch

## Migrations
If your pull request requires a migration, please *exclude the migration from the Rock.Migration project*, but submit it with your pull request. Please add a note to your pull request that provides a heads up that a migration file is present.

### CODE REVIEW

**Comment by sparkdevnetwork-service** [comment]
➤ grace hansen commented:

This is PR ready

**Comment by nairdo** [comment]
@cabal95 Daniel, I know this is an old one, but I was on the fence with this feature.  Having just re-discussed it again, we're now OK with the premise of allowing 1 (IP address configuration) to override 2 (geo location).

Are you still in need of this, and if so, would you be willing to re-merge** with the current develop branch?  If you do, we'll pull this in and it will be part of the next pre-alpha-build (in a week or so).

_** With all the changes that happened between v10 to now, when Mike went to merge this last October he ran into merge conflicts that he was not comfortable with.  Looking at it again, you probably shouldn't have too much trouble with it, right?_

**Comment by cabal95** [comment]
Yes, I will take a look and see if I can sort out the conflicts.

**Comment by cabal95** [comment]
There were so many changes since this PR that I have created a new branch and manually re-applied the changes. I looked at just fixing these conflicts but there have been so many changes it was making me dizzy trying to sort out the conflict merge.

Closing in favor of #4173.

**Pull request closed without merging**
