### PR TITLE
use system 404 mechanism if no 404 page is set

### PR DESCRIPTION
**Pull request by jweather**
## Proposed Changes
On 404 in RockRouteHandler, use the built-in 404 mechanism rather than just loading the 404 error page.  This allows custom 404 pages to see the original URL being requested rather than /page/undefined.

Fixes: #3528 

## Types of changes
What types of changes does your code introduce to Rock?
_Put an `x` in the boxes that apply_

* [x] Bugfix (non-breaking change which fixes an issue)
* [ ] New feature (non-breaking change which adds functionality, which has been approved by the core team)
* [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

* [x] I verified my PR does not include whitespace/formatting changes -- because if it does it will be closed without merging. 
* [x] I have read the [Contributing to Rock ](https://github.com/SparkDevNetwork/Rock/blob/master/.github/CONTRIBUTING.md) doc
* [x] By contributing code, I agree to license my contribution under the [Rock Community License Agreement ](https://www.rockrms.com/license)
* [ ] Unit tests pass locally with my changes
* [ ] I have added [required tests ](https://github.com/SparkDevNetwork/Rock/blob/develop/Rock.Tests/README.md) that prove my fix is effective or that my feature works
* [ ] I have included updated language for the [Rock Documentation ](https://www.rockrms.com/Learn/Documentation) (if appropriate)

### CODE REVIEW

**Comment by jweather** [comment]
Closed with no comments?

**Comment by nairdo** [comment]
@jweather Let me find out.  We've had some 'interesting' things happening with our sync tool (that keeps this in sync with our Asana system).  I'll let you know.

**Comment by jonedmiston** [comment]
@jweather looks like this was fixed already. Can you confirm the behavior you'd expect on the prealpha site?

https://prealpha.rocksolidchurchdemo.com/not-a-real-route

**Comment by jweather** [comment]
I would need to load my custom 404 handler and ensure it is receiving the full original URL in order to test -- is there a specific commit that fixes this issue?  I can try it out on our test server.

**Comment by jonedmiston** [comment]
The commit is tied to the closed issue #3528.

**Comment by jweather** [comment]
The solution to #3528 is what caused the issue I am reporting here.  Unless something else has changed since 8.7, this is still a problem.

**Comment by jonedmiston** [comment]
@jweather Ok then we might need more details on the issue.

**Comment by jweather** [comment]
The issue is that using CreateInstanceFromVirtualPath to redirect to the 404 page does not allow it to receive the original URL being entered -- instead it always receives /page/undefined.  Using the ASP.NET 404 mechanism passes the original URL correctly so the 404 page can redirect it as needed.

The requirement for a custom 404 handler comes from our need to use shortlinks to event detail pages and even to external sites, which is not supported by Rock's route handling.  I don't see this as an issue with Rock, but I would like to be able to plug in my own 404/shortlink mechanism without modifying the Rock codebase.

**Comment by jweather** [comment]
Closed with no comment?  Again?

**Comment by nairdo** [comment]
Hi @jweather I've looked at your solution and have attempted to recreate the issue you described above.  This PR would essentially remove the use of Rock's Http404Error.aspx/.cs page which is currently used to log 404 exceptions if the `Log 404s As Exceptions` Global Attribute setting is enabled: https://github.com/SparkDevNetwork/Rock/blame/develop/RockWeb/Http404Error.aspx.cs#L42

With that setting enabled, if I have a rock page with a bad link to a non-existent page, it logs the both the referring page and the 404 url:
image

If you're still having an issue, could you kindly[ log it here ](https://github.com/SparkDevNetwork/Rock/issues/new/choose) along with the steps to recreate the problem. Or if you have a suggested enhancement, please submit the idea over at https://community.rockrms.com/ideas.

**Pull request closed without merging**
