### PR TITLE
+ Fixed an issue where registrant attributes and person phone numbers weren't available to signature documents (Fixes #5518).

### LINKED ISSUE #5518: Missing registrant attribute support in signature documents
### Please go through all the tasks below

- [X] Check this box only after you have successfully completed both the above tasks

### Please provide a brief description of the problem. Please do not forget to attach the relevant screenshots from your side.

When using the signature document feature of the new obsidian registration block, phone numbers and registrant attributes aren't supported in the signature document template.

### Expected Behavior

The template should have all values filled matching what was entered into the registration

### Actual Behavior

The template is missing any phone number in a person field and all registrant attributes

### Steps to Reproduce

 This issue was reproduced using the demo site.

1. Create a signature document using the following template
```
<p>Name: {{ Registrant.FirstName }} {{ Registrant.LastName }}</p>
<p>Phone: {{ Registrant.MobilePhone }}</p>
<p>Attribute: {{ Registrant | Attribute:"TestAttr" }}</p>
```
2. Create a registration with the following fields
Screenshot 2023-07-17 at 4 19 25 PM

3. Ensure you are using the obsidian registration entry block
4. Complete the registration
Screenshot 2023-07-17 at 4 21 14 PM
---
Screenshot 2023-07-17 at 4 21 28 PM
---
[Alisha_Admin_(Signature_Document_Bug_Test_Instance).pdf](https://github.com/SparkDevNetwork/Rock/files/12073651/Alisha_Admin_.Signature_Document_Bug_Test_Instance.pdf)

### Rock Version

1.15.0.6

### Client Culture Setting

en-US

### PR DESCRIPTION
**Pull request by robotman3000**
## Notice

**In case you are submitting a non bug-fix-PR, we highly recommend you to engage in a PR discussion first.**

There are many factors we consider before accepting a pull request. This includes:
1. Whether or not the Rock system you run is a standard, main-line build. If it is not, there is a lower chance we will accept your request since it may impact some other part of the system you don't regularly use.
2. Features that would be used by less than 80% of Rock organizations, or ones that don't match the goals of Rock.

With the PR discussion we can assess your proposed changes before you start working on it so that we can come up with the best possible approach to it. This may include:
1. Coming up with an alternate approach that does not involve changes to core.
2. Advising how your proposed solution be done in a different way that is more efficient and consistent with the rest of the system.
3. Have one of our core developers make the changes for you. This may be the case if the change involves intricate tasks like an EF migration or something similar.

## Proposed Changes

Fixes: #5518

## Types of changes

What types of changes does your code introduce to Rock?
_Put an `x` in the boxes that apply_

- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality, which has been approved by the core team)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [X] This is a single-commit PR. (If not, please squash your commit and re-submit it.)
- [X] I verified my PR does not include whitespace/formatting changes -- because if it does it will be closed without merging.	
- [X] I have read the [Contributing to Rock](https://github.com/SparkDevNetwork/Rock/blob/master/.github/CONTRIBUTING.md) doc
- [X] By contributing code, I agree to license my contribution under the [Rock Community License Agreement](https://www.rockrms.com/license)
- [X] Unit tests pass locally with my changes
- [ ] I have added any required [unit tests](https://github.com/SparkDevNetwork/Rock/blob/develop/Rock.Tests.UnitTests/README.md) or [integration tests](https://github.com/SparkDevNetwork/Rock/blob/develop/Rock.Tests.Integration/README.md) that prove my fix is effective or that my feature works
- [ ] I have included updated language for the [Rock Documentation](https://www.rockrms.com/Learn/Documentation) (if appropriate)

## Further comments

Quick Note: The included screenshots are made to complement the ones provided in the issue referenced.
Screenshot 2023-07-17 at 5 17 48 PM
Screenshot 2023-07-17 at 5 18 09 PM
## Migrations
If your pull request requires a migration, please *exclude the migration from the Rock.Migration project*, but submit it with your pull request. Please add a note to your pull request that provides a heads up that a migration file is present.

### CODE REVIEW

**Comment by nlBayside** [comment]
Could this have been solved by applying `LoadAttributes()` to the `registrant` object rather than creating a new method? Looking at the code, that appears to be what is happening to the `groupMember` object when the `groupId` has a value and to the `person` object when it isn't null.
https://github.com/SparkDevNetwork/Rock/blob/274914f663908bcb21f468ea87b3a8c2deda7008/Rock.Blocks/Event/RegistrationEntry.cs#L536

For the `LavaSignatureRegistrant` class, I think the constructor could be modified to simply include a `RegistrationRegistrant` parameter and load that object's attributes with `LoadAttributes` if it isn't null. Same as the constructor does for `person` and `groupMember`.
https://github.com/SparkDevNetwork/Rock/blob/274914f663908bcb21f468ea87b3a8c2deda7008/Rock.Blocks/Event/RegistrationEntry.cs#L4054
Screen Shot 2023-07-19 at 8 49 21 AM


I think applying that existing method would be a simpler solution and be consistent with pre-existing methods in the Rock repository. Modifying the `LavaSignatureRegistrant` class to include an extra parameter would also be simpler than the solution provided in the PR and be consistent with how it is currently fetching attributes/attribute values.

**Comment by robotman3000** [comment]
That would be better, but I don't think the `RegistrationRegistrant` exists yet. At the time that the signature document is signed (Or at least previewed) the `RegistrationRegistrant` doesn't exist. It's created at the end of the registration once "Finish" is clicked. To combat this it appears that a new temporary object called `LavaSignatureRegistrant` is created that has a similar set of fields to the `RegistrationRegistrant`. The `LavaSignatureRegistrant` constructor that takes a `RegistrationRegistrant` is never called.

**Comment by nlBayside** [comment]
@robotman3000 Oh, you're totally right! I forgot to check when that method is being called. Nice solution for getting it working! I do think it's peculiar that the registrants object is of type `Record<Guid, unknown>`, rather than a type more closely resembling `AttributeValue` or even `AttributeValueCache`. If it used something close to `AttributeValueCache`, then I think the amount of code needed for this to work would be much less. You probably wouldn't have to find all the attributes from the Template Forms in that case. The Lava filters will already use `ValueFormatted` as the default. However, that would be a much much bigger change than this PR is scoped to.

Screen Shot 2023-07-19 at 1 42 34 PM

**Comment by nairdo** [comment]
@robotman3000  (& Noah @nlBayside ), thank you both to your contributions and discussion regarding this PR for the #5518 issue.  Besides cleaning up the tiny whitespace issues** in the code, we're going to make a slight adjustment to the idea here and pass the `registrantInfo` and RegistrationTemplate objects to the `LavaSignatureRegistrant(...)` constructor to contain the logic for setting the `Attributes` and `AttributeValues` collections (which come from the base class `: LavaHasAttributes`) since that was the intention of those two properties.  (And I think there is another bug in our code we'll address too.)

We'll also probably make it a bit clearer in the onscreen tips as to what is available in the `Registrant` merge field since, as you both realized, it's not a RegistrationRegistrant entity but a custom merge field which is mostly properties of a Person entity.

<hr>
** Primarily the ["Insert space within parentheses of expressions"](https://github.com/SparkDevNetwork/Rock/wiki/Coding-standards#sql-coding-standards) issues.

**Comment by ethan-sparkdevnetwork** [comment]
This was set to merge to develop (v17.0) so I cherry picked the change into 15.2.
@robotman3000 , Thanks for submitting your first PR for Rock. I have added this PR to your count in the Rock Community.
I also refactored and fixed some other issues with Lava in the Signature doc. Here are the commits for this issue:

- Cherry picked PR to branch hotfix 15.2: 19e6fb03
- Minor formating changes: bba98dbd
- Refactor Lava merge fields for signature doc templates: 6240cc8e
- Updated template tips on SignatureDocumentTemplateDetail: ef43126a

**Pull request closed without merging**
