### PR TITLE
Added the ability to view and edit custom attribute values for metric entity on the metric detail block

### PR DESCRIPTION
**Pull request by briankalwat**
## Proposed Changes

This PR adds the ability to use set values of metric attributes on the metric detail block.

## Types of changes

What types of changes does your code introduce to Rock?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality, which has been approved by the core team)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] This is a single-commit PR. (If not, please squash your commit and re-submit it.)
- [x] I verified my PR does not include whitespace/formatting changes -- because if it does it will be closed without merging.	
- [x] I have read the [Contributing to Rock](https://github.com/SparkDevNetwork/Rock/blob/master/.github/CONTRIBUTING.md) doc
- [x] By contributing code, I agree to license my contribution under the [Rock Community License Agreement](https://www.rockrms.com/license)
- [ ] Unit tests pass locally with my changes
- [ ] I have added [required tests](https://github.com/SparkDevNetwork/Rock/blob/develop/Rock.Tests/README.md) that prove my fix is effective or that my feature works
- [ ] I have included updated language for the [Rock Documentation](https://www.rockrms.com/Learn/Documentation) (if appropriate)

### CODE REVIEW

**Comment by jonedmiston** [comment]
Thanks Brian! What kind of attributes are you adding to metrics. Interested in the use cases for the docs.

**Comment by briankalwat** [comment]
> Thanks Brian! What kind of attributes are you adding to metrics. Interested in the use cases for the docs.

@jonedmiston we have metric dashboards that reference multiple metrics depending on the route used to access the page. Those metrics have report pages associated with them (reports that give campus staff insights into how they can improve these metrics – for instance, a fuse attendance metric would be linked to a report page with a report that surfaces contact info for students with attendance to fuse who haven't attended the past three weeks - so they could be followed up with). Right now these report pages are statically defined on the page. With this addition, we can associate the report pages to the metrics dynamically.

**Comment by nairdo** [comment]
@briankalwat I tested this and it works as-is, but did you _intend_ it to NOT show the attributes on the view mode of the metric details?  _Normally we've been including them on the view panel as well as the edit panel._

**Comment by briankalwat** [comment]
@nairdo I didn't include them in the view because we didn't do that for the Site Detail/Tag Detail blocks - but if that is a standard then I can work on adding them to all three. Whatever y'all think is best!

**Pull request merged**
