### PR TITLE
+ Added a new Lava Filter to get the End Date from an iCal feed.

### PR DESCRIPTION
**Pull request by treyhendon**
# Contributor Agreement
Yes

# Context
Needed to expose that an event was happening from 1pm until 3pm.

# Goal
Adds a new Lava filter that parses the End Date(s) from the iCal feed.

# Strategy
Copy/Paste from existing code in Lava filters changing where necessary.

# Possible Implications
More Filters!

# Screenshots
ical_date

# Documentation
```
Returns a list of upcoming end dates from an iCal string or List of iCal strings.

Additional Details
This filter takes an optional parameter of the number of upcoming occurrences to display. The default is 1. A text value of 'All' can also be used to return all the occurrences.

Example:
"EventItemCampuses": {
    [
        { 
            "ContactEmail": "jenny@rocksolidchurchdemo.com",
            "EventItemSchedules": [
                { 
                    "Schedule": {
                        ... ,
                        "iCalendarContent": "BEGIN:VCALENDAR VERSION:2.0 PRODID:-//ddaysof...",
                        ... ,
                    }
                }
            ]
        }
    ]
}
{% assign upcomingEndDates =  EventItemSchedules | Select:'Schedule' | Select:'iCalendarContent' | EndDatesFromICal:2 %}

<ul>
{% for endDate in upcomingEndDates %}
    <li>{{ endDate }}</li>
{% endfor %}
</ul>
<ul>
    <li>7/15/2015 8:00:00 PM</li>
    <li>7/16/2015 8:00:00 PM</li>
</ul>

```

### CODE REVIEW

**Comment by edmistj** [comment]
Can you provide the sample input, statement and output for the Lava docs?

**Comment by treyhendon** [comment]
Sure thing, the initial text has been updated.

**Comment by nairdo** [comment]
@treyhendon I'm going to pull this request in and then I'll be adding some additional unit tests to the new Rock.Tests RockFilters tests to verify the functionality.   From this point forward I'll be asking everyone to follow the same approach (see example in [RockFiltersTests](https://raw.githubusercontent.com/SparkDevNetwork/Rock/develop/Rock.Tests/Rock/Lava/RockFiltersTests.cs)) if they add or change any of Rock's lava filters.

**Comment by nairdo** [comment]
@treyhendon after further discussions and for better consistency, we're going use your work but change it to just add a new optional parameter ('enddatetime') to the existing `DatesFromICal` filter.  I hope this doesn't cause you too much trouble -- and thanks for the code.

**Comment by treyhendon** [comment]
Looks great!  I love the idea of having it as an optional parameter.  We weren't using it in production anywhere yet (was waiting on main line release) so doesn't hurt us at all.  Thanks!

**Pull request merged**
