### PR TITLE
Change ItemPicker:  ClientID instead of ID

### PR DESCRIPTION
**Pull request by demersus**
See issue #1261

### CODE REVIEW

**Comment by mikepetersonccv** [comment]
@demersus Yep, this is definitely a bug. Can we fix it a slightly different way? Basically, instead of using ClientId for the control prefixes, etc, how about just changing RegisterJavaScript() and RenderControls() use the .ClientID instead of the .Id

**Comment by demersus** [comment]
That sounds good. I will update the merge request tomorrow.

**Comment by mikepetersonccv** [comment]
@demersus Looks good! Thanks for finding that issue and fixing it.

**Comment by demersus** [comment]
@mikepetersonccv  You're welcome.  Thanks for building this system!

**Pull request merged**
