### PR TITLE
Feature jm fix defined value looks ups

### PR DESCRIPTION
**Pull request by JoshuaMaiorino**
## Proposed Changes

This adds new logic for Defined Value Lookups for Suffix and Titles that ignores case all together.

Fixes: 

What types of changes does your code introduce to Rock?
_Put an `x` in the boxes that apply_

- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality, which has been approved by the core team)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [X] I verified my PR does not include whitespace/formatting changes -- because if it does it will be closed without merging.	
- [X] I have read the [Contributing to Rock](https://github.com/SparkDevNetwork/Rock/blob/master/.github/CONTRIBUTING.md) doc
- [X] By contributing code, I agree to license my contribution under the [Rock Community License Agreement](https://www.rockrms.com/license)
- [ ] Unit tests pass locally with my changes
- [ ] I have added [required tests](https://github.com/SparkDevNetwork/Rock/blob/develop/Rock.Tests/README.md) that prove my fix is effective or that my feature works
- [ ] I have included updated language for the [Rock Documentation](https://www.rockrms.com/Learn/Documentation) (if appropriate)

### CODE REVIEW

**Comment by jonedmiston** [comment]
@JoshuaMaiorino can you add some more info on the use-case for this?

**Comment by JoshuaMaiorino** [comment]
Hi Jon.  There's currently often times errors when importing data.  The error is given key not in dictionary.  This happens when Data to be imported do not have defined lists, but rather free text for things like title, and suffix.  Rock first checks against the list to defined types in Rock.  During this check, it ignores case.  If there are any new Values, it adds them.  However, when it assigned the defined value to the import person, it uses a dictionary with the text value as the key.  Those are case sensitive.  So this change is to make both title and suffix assignments ignore the Case of the defined type value as well.

**Comment by jonedmiston** [comment]
@JoshuaMaiorino awesome thanks!

**Comment by nairdo** [comment]
Thanks @JoshuaMaiorino!  We're super thankful with your efforts to help make Rock better! :) Can you do one small thing?  Can you just squash all the commits and resubmit as a single commit? 

_(We're really in need of keeping the develop branch much cleaner with single-commit-PRs and we are making this a requirement now.)_

**Comment by nairdo** [comment]
@JoshuaMaiorino We're hoping to do a PR fest in the next few weeks, so if you still want this PR please re-submit with all 10 commits squashed into one.

**Comment by JoshuaMaiorino** [comment]
I've created a new PR. #3742

**Pull request closed without merging**
