### PR TITLE
Fixed Credit Card validation for NMI, #2084

### PR DESCRIPTION
**Pull request by garrettjohnson**
# Contributor Agreement
_Have you filled out and sent your [Spark Contributor Agreement](http://www.rockrms.com/Content/RockExternal/Misc/Contributor%20Agreement.pdf) to secretary [at] sparkdevnetwork.org?_ Yes.

# Context

#2084, all Rock pages that accept a 3 Step gateway currently will allow blank credit cards or no ACH info. 

# Goal

Replace `creditCardTypeDetector` with Stripe's PaymentJS. Which will allow for detection of card type, as well as validation. 

# Strategy
Use client side validation to prevent submission of blank credit card and ACH fields.

# Tests
N/A

# Possible Implications
To allow for more consistency and compatibility, both the credit card and CVC fields are set to html5 tel, added autocomplete, and changed CSS classes from `credit-card` to `cc-num`.

# Screenshots
N/A

# Documentation
N/A

### CODE REVIEW

**Comment by dcs619** [comment]
@garrettjohnson I'm guessing this hasn't been pulled in due to the JS library change, but is this finished or already in production somewhere?  We have several people asking about this issue.

**Comment by dcs619** [comment]
Also, since this is a bugfix and v7 won't be out till later this year, this should probably be in hotfix-1.6.10.

**Comment by edmistj** [comment]
@dcs619 We ask that PRs are made to the develop branch. We'll handle getting them to the right hotfix.

**Comment by azturner** [comment]
@garrettjohnson This is an awesome update and love the cc number formatting that it does. I kept having an issue though with it showing the "updating" view whenever it got to the confirmation page and would never return from that. This was occurring using both the test gateway and the NMI gateway:
give now external website

**Comment by garrettjohnson** [comment]
I finally have time to get to it this weekend and week. The js card validation needs to be conditionally triggered depending on if the cc field tab was visible. I think I found a working validator for ACH routing numbers as well. Not sure if I committed that yet 

Garrett Johnson

**Comment by dcs619** [comment]
Any more feedback on this?

**Pull request closed without merging**
