### PR TITLE
[EN] Update the dynamic data block with better filters

### PR DESCRIPTION
**Pull request by dcs619**
- Updates the dynamic data filter with DBA-friendly syntax
- Allows filtering by any text in the column, not just at the beginning
- Sets the filter visibility on by default 

@edmistj any issues with item 3?  Every time we've turned the filter on for a DD block, users have been ecstatic.

### CODE REVIEW

**Comment by edmistj** [comment]
@dcs619 I think #3 is good. Could we move the block setting though to the edit screen. Most of the meat of that block is configured on the custom edit screen.

**Comment by dcs619** [comment]
@edmistj Should I move the `Paneled Grid` attribute as well?  It's the only one not in the custom edit screen.

**Comment by edmistj** [comment]
Sure, do you mean 'Update Page' though?

**Comment by dcs619** [comment]
@edmistj I was referring to [this](https://github.com/SparkDevNetwork/Rock/blob/develop/RockWeb/Blocks/Reporting/DynamicData.ascx.cs#L65).  In any case those changes are pushed.

**Pull request merged**
