### PR TITLE
- Fixed extra spaces in names and incorrect param/code comments (Fixes 2554)

### PR DESCRIPTION
**Pull request by tom-powers**
##  Proposed Changes

Mkinyon identified an issue with extra spaces being added in family titles when there are 2 adults with different last names.  I was able to replicate this issue as well, and it was due to not having a suffix in each name.  I also noticed that an extra space was being added for a single person as well.  I implemented mkinyon's suggestion from 10/19/2017 to address both issues.  I also updated the param and code comments as they weren't up to date.

Fixes: #2554 

## Types of changes

What types of changes does your code introduce to Rock?
_Put an `x` in the boxes that apply_

- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality, which has been approved by the core team)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [X] This is a single-commit PR. (If not, please squash your commit and re-submit it.)
- [X] I verified my PR does not include whitespace/formatting changes -- because if it does it will be closed without merging.	
- [X] I have read the [Contributing to Rock](https://github.com/SparkDevNetwork/Rock/blob/master/.github/CONTRIBUTING.md) doc
- [X] By contributing code, I agree to license my contribution under the [Rock Community License Agreement](https://www.rockrms.com/license)
- [X] Unit tests pass locally with my changes
- [ ] I have added [required tests](https://github.com/SparkDevNetwork/Rock/blob/develop/Rock.Tests/README.md) that prove my fix is effective or that my feature works
- [ ] I have included updated language for the [Rock Documentation](https://www.rockrms.com/Learn/Documentation) (if appropriate)

## Further comments
I considered using RTRIM but decided to go with ISNULL instead.

## Documentation
n/a

## Migrations
n/a

-----
Assigned to MasonK for QA Testing

### CODE REVIEW

**Comment by jonedmiston** [comment]
Thanks @tom-powers !

**Comment by mkinyon** [comment]
@nairdo I tested the pull request and it is working perfectly.  Thanks @tom-powers!

**Comment by nairdo** [comment]
Thanks @mkinyon !  This is now ready for merging, but because it will need a migration to update the two stored procedures in a fashion similar to [this migration](https://github.com/SparkDevNetwork/Rock/blob/release-1.5.0/Rock.Migrations/Migrations/Version%205.0/Version%201.5.0/201602161036322_AttendanceAnalyticsQuery_NonAttendees.sql)  it's on-hold until we unfreeze the migration token in the develop branch.

**Comment by MikeDPeterson** [comment]
Looks good, Thanks @mkinyon   and @tom-powers!

**Pull request merged**
