### PR TITLE
+ Added option for Filter Group Condition = "True/False" to implement…

### PR DESCRIPTION
**Pull request by MrUpsideDown**
… logical "NOT" operations for Filter Groups. This allows existing Filter Conditions to be negated.

### CODE REVIEW

**Comment by MrUpsideDown** [comment]
Another area where this is particularly useful is where we have a Data View that identifies a specific set of people, and we want to exclude these people from the results of a second Data View (possibly with combined with other conditions). Without the True/False modification, the only alternative is to re-create the inverse of the first Data View, which is tedious and introduces the potential for error if the logic of the first Data View is somewhat complex.

**Comment by arranf** [comment]
This is ace. Thank you David!

**Comment by azturner** [comment]
Sounds good. We'll pull and take a look.

**Comment by MrUpsideDown** [comment]
@arranf You're welcome - I hope this change simplifies a few queries for you, just as it has for us. :-)

**Pull request merged**
