### PR TITLE
[EN] Added ability to set default frequency and dollar amounts for TransactionEntry

### PR DESCRIPTION
**Pull request by cabal95**
# Contributor Agreement
_Have you filled out and sent your [Spark Contributor Agreement](http://www.rockrms.com/Content/RockExternal/Misc/Contributor%20Agreement.pdf) to secretary [at] sparkdevnetwork.org?_

**Yes**

# Context
_What is the problem you encountered that lead to you creating this pull request?_

See #2359 for discussion.

# Goal
_What will this pull request achieve and how will this fix the problem?_

Rock our Finance Team's world.

# Strategy
_How have you implemented your solution?_

New URL formats supported:
* `AccountIds=AccountId^Amount^UserEditable[,...]`
* `AccountGlCodes=AccountId^Amount^UserEditable[,...]`
  * Amount and UserEditable are optional in both formats.
  * Example: `?AccountIds=2^50.00^false`
* `Frequency=DefinedValueId^UserEditable`
  * UserEditable is optional.
  * Example: `&Frequency=133,false`

# Notes

Special care taken to ensure that the Javascript code to calculate the total still works as expected when an account is not user-editable.

No new block setting was added for enabling support of setting Frequency from the URL. That doesn't seem like a security issue like it could be with Accounts.

# Tests
_If your code is a new method or function (that doesn't need a mock database or SqlServerTypes library) and can be Xunit tested [see example](https://github.com/SparkDevNetwork/Rock/blob/develop/Rock.Tests/Rock/Lava/RockFiltersTests.cs) be sure your pull request includes the corresponding unit tests in the Rock.Tests project. In all cases *you* MUST test your code before submitting a pull request._

n/a

# Possible Implications
_What could this change potentially impact? Are there any security considerations? Where could this potentially affect backwards compatibility?_

n/a

# Screenshots
_Provide us some screenshots if your pull request either alters existing UI or provides new UI. Arrows and labels are helpful._

screen shot 2017-07-20 at 11 46 48 am

# Documentation
_If your change effects the UI or needs to be documented in one of the existing [user guides](http://www.rockrms.com/Learn/Documentation), please provide the brief write-up here:_

n/a?

### CODE REVIEW

**Comment by edmistj** [comment]
@MikeDPeterson David will review this to merge it in. Could you though update our document for all of the options on the TransactionEntry block. It's on Dropbox -> RockRMS -> Documentation -> Transaction Entry Cheat Sheet

I'll then have Amy add it to the Financial Docs.

**Comment by MikeDPeterson** [comment]
Ok. The doc is updated and I updated help text in the the Block a little bit too.

[cid:image002.png@01D32AE6.34644EB0]

**Comment by edmistj** [comment]
OK, Amy is going to come see you.
-Jon


[https://rockrms.blob.core.windows.net/email-sig/jon.jpg]
[https://rockrms.blob.core.windows.net/email-sig/spark-mini.jpg]<http://www.rockrms.com/>

Jon Edmiston

p:  623.777.3377
e:  jon@sparkdevnetwork.org
w:  www.rockrms.com<http://www.rockrms.com/>

[LinkedIn]<www.linkedin.com/in/jonedmiston>  [Twitter] <twitter.com/jonedmiston>


<http://www.rockrms.com/emailsignature>

**Comment by arranf** [comment]
@edmistj Not sure this was meant to end up here!

**Pull request merged**
